/* 
 * Actualizat los tipos de identificacion de la tabla de cliente
 */
/**
 * Author:  Carlos
 * Created: 24/07/2018
 */
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='R' WHERE LENGTH(IDENTIFICACION)=13;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='C' WHERE LENGTH(IDENTIFICACION)=10;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='F' WHERE IDENTIFICACION='9999999999999';
