/* 
 * Actualizat los tipos de identificacion de la tabla de cliente
 */
/**
 * Author:  Carlos
 * Created: 24/07/2018
 */
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET IDENTIFICACION='9999999999999',RAZON_SOCIAL='Consumidor Final',NOMBRE_LEGAL='Consumidor Final',NOMBRES='Consumidor',APELLIDOS='Final',TIPO_OPERADOR='A' WHERE IDENTIFICACION='9999999999' or IDENTIFICACION='9999999999999' ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='R' WHERE LENGTH(IDENTIFICACION)=13;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='C' WHERE LENGTH(IDENTIFICACION)=10;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='F' WHERE IDENTIFICACION='9999999999999';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='R' WHERE TIPO_IDENTIFICACION='RUC';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='C' WHERE TIPO_IDENTIFICACION='CEDULA';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='F' WHERE TIPO_IDENTIFICACION='CONSUMIDOR FINAL';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='P' WHERE TIPO_IDENTIFICACION='PASAPORTE / IDENTIFICACION TRIBUTARIA DEL EXTERIOR';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.1)*/
ALTER TABLE EMPRESA ALTER RAZON_SOCIAL SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.1)*/
ALTER TABLE EMPRESA ALTER NOMBRE_LEGAL SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.1)*/
ALTER TABLE EMPRESA ALTER DIRECCION SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.3)*/
UPDATE RUBROS_NIVEL  SET ESTADO='A' ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.4)*/
UPDATE CLIENTE SET ESTADO='A' WHERE ESTADO IS NULL; /* Actualizacion con algunos clientes que se migraron sin estado especial para MyGoldenWorld*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.5)*/
DELETE FROM RUBRO_PLANTILLA_ESTUDIANTE  WHERE ESTUDIANTE_INSCRITO_ID IN (SELECT EI.ID FROM RUBRO_PLANTILLA_ESTUDIANTE PE,ESTUDIANTE_INSCRITO EI WHERE PE.ESTUDIANTE_INSCRITO_ID=EI.ID AND EI.ESTADO='E');/*Eliminar datos erroneos creados en las plantillas mensuales con estudiantes_inscritos eliminados*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Efectivo' WHERE CODIGO='01';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Compensación' WHERE CODIGO='15';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Tarjeta débito' WHERE CODIGO='16';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Dinero electrónico' WHERE CODIGO='17';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Tarjeta prepago' WHERE CODIGO='18';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Tarjeta crédito' WHERE CODIGO='19';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Otros' WHERE CODIGO='20';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Endoso títulos' WHERE CODIGO='21';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE RUBROS_NIVEL SET ESTADO='A' WHERE ESTADO IS NULL;/*Actualizando rubros del nivel que se crearon desde la plantilla y se estaban generando sin estado*/
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.7)*/
UPDATE RUBRO_PLANTILLA SET ESTADO='A' WHERE ESTADO IS NULL;/*Actualizar con el estado activo a todos los rubros de la plantilla creados*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.7)*/
CREATE FUNCTION TEXTO_ESTANDAR(texto VARCHAR(5000)) RETURNS VARCHAR(5000) 
    PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA 
    EXTERNAL NAME 'ec.com.codesoft.codefaclite.utilidades.varios.UtilidadesDerby.normalizarTextoDerby'; /*Agregar funcion para normalizar los texto y poder hacer busquedas sin importar acentos*/
