/* 
 * En este script voy solo a utilizar los indices de las tablas porque eso ayuda a mejorar el rendimiento bastante
*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_FACTURA_DETALLE_FACTURA_ID ON FACTURA_DETALLE (FACTURA_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_FACTURA_FORMA_PAGO_FACTURA_ID ON FACTURA_FORMA_PAGO (FACTURA_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_FACTURA_ADICIONAL_FACTURA_ID ON FACTURA_ADICIONAL (FACTURA_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_REEMBOLSO_DETALLE_FACTURA_ID ON REEMBOLSO_DETALLE (FACTURA_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_CARTERA_DETALLE_CARTERA_ID ON CARTERA_DETALLE (CARTERA_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_CARTERA_CRUCE_AFECTA_ID ON CARTERA_CRUCE (CARTERA_AFECTA_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_CARTERA_CRUCE_DETALLE_ID ON CARTERA_CRUCE (CARTERA_DETALLE_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_PERMISO_VENTANA_PERFIL_ID ON PERMISO_VENTANA (PERFIL_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_KARDEX_DETALLE_KARDEX_ID ON KARDEX_DETALLE (KARDEX_ID);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.3.1.3.7)*/
CREATE INDEX IDX_KARDEX_PRODUCTO_ID ON KARDEX (PRODUCTO_ID);