/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.crm.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.corecodefaclite.ayuda.AyudaCodefacAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.views.GeneralPanelInterface;
import ec.com.codesoft.codefaclite.crm.test.EjemploCrm;
import ec.com.codesoft.codefaclite.servidor.entity.SriIdentificacion;
import ec.com.codesoft.codefaclite.servidor.entity.enumerados.ClienteEnumEstado;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PC
 */
public abstract class ClienteForm extends ControladorCodefacInterface {

    /**
     * Creates new form clienteForm
     */
    public ClienteForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCaracteristicasGenerales = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboIdentificacion = new javax.swing.JComboBox<>();
        jTextIdentificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboTipoCliente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDireccion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextExtension = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jTextNombreSocial = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cliente");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/persona-ico.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 387));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DETALLE DEL CLIENTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);

        jPanelCaracteristicasGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Clientes"));
        jPanelCaracteristicasGenerales.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextNombres, gridBagConstraints);

        jLabel3.setText("Tipo Identificación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jComboIdentificacion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextIdentificacion, gridBagConstraints);

        jLabel5.setText("Tipo Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel5, gridBagConstraints);

        jComboTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "SUJETO RETENIDO", "DESTINATARIO" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jComboTipoCliente, gridBagConstraints);

        jLabel6.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel6, gridBagConstraints);

        jTextAreaDireccion.setColumns(20);
        jTextAreaDireccion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDireccion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jScrollPane1, gridBagConstraints);

        jLabel7.setText("Teléfono Convencional:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextTelefono, gridBagConstraints);

        jLabel8.setText("Extensión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextExtension, gridBagConstraints);

        jLabel9.setText("Teléfono Celular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextCelular, gridBagConstraints);

        jLabel10.setText("Correo Electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextCorreo, gridBagConstraints);

        jLabel4.setText("Identificación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel4, gridBagConstraints);

        jLabel11.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel11, gridBagConstraints);

        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(cmbEstado, gridBagConstraints);

        jLabel13.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel13, gridBagConstraints);

        jLabel14.setText("Razón Social:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanelCaracteristicasGenerales.add(jLabel14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(jTextApellidos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(jTextNombreSocial, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanelCaracteristicasGenerales, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ClienteEnumEstado> cmbEstado;
    private javax.swing.JComboBox<SriIdentificacion> jComboIdentificacion;
    private javax.swing.JComboBox<String> jComboTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCaracteristicasGenerales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextArea jTextAreaDireccion;
    private javax.swing.JTextField jTextCelular;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextExtension;
    private javax.swing.JTextField jTextIdentificacion;
    private javax.swing.JTextField jTextNombreSocial;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getjComboTipoCliente() {
        return jComboTipoCliente;
    }

    public void setjComboTipoCliente(JComboBox<String> jComboTipoCliente) {
        this.jComboTipoCliente = jComboTipoCliente;
    }

    public JPanel getjPanelCaracteristicasGenerales() {
        return jPanelCaracteristicasGenerales;
    }

    public void setjPanelCaracteristicasGenerales(JPanel jPanelCaracteristicasGenerales) {
        this.jPanelCaracteristicasGenerales = jPanelCaracteristicasGenerales;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, min = 0, expresionRegular = "^[A-Za-z0-9\\s.\\_\\-\\ ]*$", nombre = "Direccion")
    public JTextArea getjTextAreaDireccion() {
        return jTextAreaDireccion;
    }

    public void setjTextAreaDireccion(JTextArea jTextAreaDireccion) {
        this.jTextAreaDireccion = jTextAreaDireccion;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0][0-9]{9}$", nombre = "Celular")
    public JTextField getjTextCelular() {
        return jTextCelular;
    }

    public void setjTextCelular(JTextField jTextCelular) {
        this.jTextCelular = jTextCelular;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$", nombre = "Correo Electronico")
    public JTextField getjTextCorreo() {
        return jTextCorreo;
    }

    public void setjTextCorreo(JTextField jTextCorreo) {
        this.jTextCorreo = jTextCorreo;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, min = 0, expresionRegular = "^[0-9]*$", nombre = "Extension")
    public JTextField getjTextExtension() {
        return jTextExtension;
    }

    public void setjTextExtension(JTextField jTextExtension) {
        this.jTextExtension = jTextExtension;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(personalizado = {"validarCedula"}, requerido = true, min = 0, max = 10, expresionRegular = "", nombre = "Identificacion")
    public JTextField getjTextIdentificacion() {
        return jTextIdentificacion;
    }

    public void setjTextIdentificacion(JTextField jTextIdentificacion) {
        this.jTextIdentificacion = jTextIdentificacion;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, min = 5, max = 100, expresionRegular = "^[A-Za-z0-9\\s.\\_\\-\\ ]*$", nombre = "Nombre Social")
    public JTextField getjTextNombreSocial() {
        return jTextNombres;
    }

    public void setjTextNombreSocial(JTextField jTextNombre) {
        this.jTextNombres = jTextNombre;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0][0-9]{8}$", nombre = "Telefono")
    public JTextField getjTextTelefono() {
        return jTextTelefono;
    }

    public void setjTextTelefono(JTextField jTextTelefono) {
        this.jTextTelefono = jTextTelefono;
    }

    public JComboBox<SriIdentificacion> getjComboIdentificacion() {
        return jComboIdentificacion;
    }

    public void setjComboIdentificacion(JComboBox<SriIdentificacion> jComboIdentificacion) {
        this.jComboIdentificacion = jComboIdentificacion;
    }

    public JComboBox<ClienteEnumEstado> getCmbEstado() {
        return cmbEstado;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, min = 5, max = 200, expresionRegular = "^[A-Za-z0-9\\s.\\_\\-\\ ]*$", nombre = "Apellidos")
    public JTextField getjTextApellidos() {
        return jTextApellidos;
    }

    public void setjTextApellidos(JTextField jTextApellidos) {
        this.jTextApellidos = jTextApellidos;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, min = 5, max = 200, expresionRegular = "^[A-Za-z0-9\\s.\\_\\-\\ ]*$", nombre = "Nombres")
    public JTextField getjTextNombres() {
        return jTextNombres;
    }

    public void setjTextNombres(JTextField jTextNombres) {
        this.jTextNombres = jTextNombres;
    }

}
