/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.crm.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.corecodefaclite.ayuda.AyudaCodefacAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.views.GeneralPanelInterface;
import ec.com.codesoft.codefaclite.servidor.entity.ImpuestoDetalle;
import ec.com.codesoft.codefaclite.servidor.entity.enumerados.EnumSiNo;
import ec.com.codesoft.codefaclite.servidor.entity.enumerados.TipoProductoEnum;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public abstract class ProductoForm extends ControladorCodefacInterface{

    public JComboBox<TipoProductoEnum> getComboTipoProducto() {
        return comboTipoProducto;
    }

    public void setComboTipoProducto(JComboBox<TipoProductoEnum> jComboTipoProducto) {
        this.comboTipoProducto = jComboTipoProducto;
    }
    /*
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=false ,expresionRegular = "^[A-Za-z0-9.\\_\\-\\\\s]*$",nombre = "Codigo Auxiliar", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTextCodigoAuxiliar() {
        return txtCodigoUPC;
    }

    public void setTextCodigoAuxiliar(JTextField jTextCodigoAuxiliar) {
        this.txtCodigoUPC = jTextCodigoAuxiliar;
    }
    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true ,expresionRegular = "^[A-Za-z0-9.\\_\\-\\\\s]*$",nombre = "Codigo Principal", expresionRegularMensaje = "No se permiten caracteres esperciales")
    public JTextField getTextCodigoPrincipal() {
        return textCodigoPersonalizado;
    }

    public void setTextCodigoPrincipal(JTextField jTextCodigoPrincipal) {
        this.textCodigoPersonalizado = jTextCodigoPrincipal;
    }*/
    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true, expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$",nombre = "Nombre", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTextNombre() {
        return textNombre;
    }

    public void setTextNombre(JTextField jTextNombre) {
        this.textNombre = jTextNombre;
    }
    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true, expresionRegular = "^[0-9]+([.][0-9]+)?$", expresionRegularMensaje = "Solo se permite numeros enteros y decimales")
    public JTextField getTextValorUnitario() {
        return textValorUnitario;
    }

    public void setTextValorUnitario(JTextField jTextValorUnitario) {
        this.textValorUnitario = jTextValorUnitario;
    }

    public JComboBox<ImpuestoDetalle> getComboIce() {
        return comboIce;
    }

    public void setComboIce(JComboBox<ImpuestoDetalle> comboIce) {
        this.comboIce = comboIce;
    }

    public JComboBox<ImpuestoDetalle> getComboIrbpnr() {
        return comboIrbpnr;
    }

    public void setComboIrbpnr(JComboBox<ImpuestoDetalle> comboIrbpnr) {
        this.comboIrbpnr = comboIrbpnr;
    }

    public JComboBox<ImpuestoDetalle> getComboIva() {
        return comboIva;
    }

    public void setComboIva(JComboBox<ImpuestoDetalle> comboIva) {
        this.comboIva = comboIva;
    }
    
    

    /**
     * Creates new form ProductoForm
     */
    public ProductoForm() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoPersonalizado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoUPC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboTipoProducto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textValorUnitario = new javax.swing.JTextField();
        lblEspacio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoEAN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        comboIva = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboIce = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        comboIrbpnr = new javax.swing.JComboBox<>();
        lblEspacio2 = new javax.swing.JLabel();
        lblEspacioBlanco = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cmbGarantia = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtCantidadMinima = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtStockInicial = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPrecioDistribuidor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPrecioTarjeta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCaracteristica = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtImagenProducto = new javax.swing.JTextField();
        btnBuscarImagen = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        cmbCategoriaProducto = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosEnsamble = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtProductoEnsamble = new javax.swing.JTextField();
        btnBuscarProductoEnsamble = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadEnsamble = new javax.swing.JTextField();
        btnAgregarEnsamble = new javax.swing.JButton();
        btnEditarEnsamble = new javax.swing.JButton();
        btnEliminarEnsamble = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Producto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(520, 374));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Características Generales"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Código Personalizado: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtCodigoPersonalizado, gridBagConstraints);

        jLabel3.setText("Código UPC: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtCodigoUPC, gridBagConstraints);

        jLabel4.setText("Tipo de Producto: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(comboTipoProducto, gridBagConstraints);

        jLabel5.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(jLabel5, gridBagConstraints);

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(textNombre, gridBagConstraints);

        jLabel6.setText("P.Venta Publico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(jLabel6, gridBagConstraints);

        textValorUnitario.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(textValorUnitario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblEspacio, gridBagConstraints);

        jLabel1.setText("Código EAN: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtCodigoEAN, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nota: Solo es necesario ingresar un solo código para el producto ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        jPanel1.add(jLabel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Impuestos Aplicables"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel10.setText("IVA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 20);
        jPanel2.add(jLabel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(comboIva, gridBagConstraints);

        jLabel11.setText("ICE:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 20);
        jPanel2.add(jLabel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(comboIce, gridBagConstraints);

        jLabel12.setText("IRBPNR:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 20);
        jPanel2.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(comboIrbpnr, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        jPanel2.add(lblEspacio2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(lblEspacioBlanco, gridBagConstraints);

        jTabbedPane1.addTab("Info General", jPanel3);

        jLabel15.setText("Garantia:");

        jLabel20.setText("Cantidad Minima:");

        txtCantidadMinima.setText("0");

        jLabel21.setText("Stock Inicial:");

        txtStockInicial.setText("0");

        jLabel23.setText("Ubicacion:");

        jLabel25.setText("P.Venta Distribuidor:");

        txtPrecioDistribuidor.setText("0");

        jLabel26.setText("P.Venta Con Tarjeta:");

        txtPrecioTarjeta.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)
                            .addComponent(jLabel15)
                            .addComponent(jLabel25))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtPrecioDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtPrecioDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtPrecioTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Info Inventario", jPanel4);

        jLabel16.setText("Marca:");

        jLabel17.setText("Caracteristicas:");

        txtCaracteristica.setColumns(20);
        txtCaracteristica.setRows(5);
        jScrollPane2.setViewportView(txtCaracteristica);

        jLabel18.setText("Imagen:");

        btnBuscarImagen.setText("Buscar");

        jLabel19.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane3.setViewportView(txtObservaciones);

        jLabel22.setText("Categoria:");

        cmbCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbCategoriaProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, 202, Short.MAX_VALUE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImagenProducto, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarImagen)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmbCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Info Adicional", jPanel5);

        tblDatosEnsamble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatosEnsamble);

        jLabel9.setText("Producto:");

        txtProductoEnsamble.setEditable(false);

        btnBuscarProductoEnsamble.setText("Buscar");

        jLabel13.setText("Cantidad:");

        txtCantidadEnsamble.setText("1");

        btnAgregarEnsamble.setText("+");

        btnEditarEnsamble.setText("Editar");

        btnEliminarEnsamble.setText("X");
        btnEliminarEnsamble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEnsambleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarEnsamble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarEnsamble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEnsamble)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadEnsamble, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtProductoEnsamble, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarProductoEnsamble)))
                        .addContainerGap(91, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtProductoEnsamble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProductoEnsamble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEnsamble)
                    .addComponent(btnEditarEnsamble)
                    .addComponent(btnEliminarEnsamble)
                    .addComponent(jLabel13)
                    .addComponent(txtCantidadEnsamble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Emsamble", jPanel6);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
    }//GEN-LAST:event_textNombreActionPerformed

    private void btnEliminarEnsambleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEnsambleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEnsambleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEnsamble;
    private javax.swing.JButton btnBuscarImagen;
    private javax.swing.JButton btnBuscarProductoEnsamble;
    private javax.swing.JButton btnEditarEnsamble;
    private javax.swing.JButton btnEliminarEnsamble;
    private javax.swing.JComboBox<String> cmbCategoriaProducto;
    private javax.swing.JComboBox<ec.com.codesoft.codefaclite.servidor.entity.enumerados.EnumSiNo> cmbGarantia;
    private javax.swing.JComboBox<ImpuestoDetalle> comboIce;
    private javax.swing.JComboBox<ImpuestoDetalle> comboIrbpnr;
    private javax.swing.JComboBox<ImpuestoDetalle> comboIva;
    private javax.swing.JComboBox<TipoProductoEnum> comboTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEspacio;
    private javax.swing.JLabel lblEspacio2;
    private javax.swing.JLabel lblEspacioBlanco;
    private javax.swing.JTable tblDatosEnsamble;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textValorUnitario;
    private javax.swing.JTextField txtCantidadEnsamble;
    private javax.swing.JTextField txtCantidadMinima;
    private javax.swing.JTextArea txtCaracteristica;
    private javax.swing.JTextField txtCodigoEAN;
    private javax.swing.JTextField txtCodigoPersonalizado;
    private javax.swing.JTextField txtCodigoUPC;
    private javax.swing.JTextField txtImagenProducto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPrecioDistribuidor;
    private javax.swing.JTextField txtPrecioTarjeta;
    private javax.swing.JTextField txtProductoEnsamble;
    private javax.swing.JTextField txtStockInicial;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtCodigoEAN() {
        return txtCodigoEAN;
    }

    public void setTxtCodigoEAN(JTextField txtCodigoEAN) {
        this.txtCodigoEAN = txtCodigoEAN;
    }

    public JTextField getTxtCodigoPersonalizado() {
        return txtCodigoPersonalizado;
    }

    public void setTxtCodigoPersonalizado(JTextField txtCodigoPersonalizado) {
        this.txtCodigoPersonalizado = txtCodigoPersonalizado;
    }

    public JTextField getTxtCodigoUPC() {
        return txtCodigoUPC;
    }

    public void setTxtCodigoUPC(JTextField txtCodigoUPC) {
        this.txtCodigoUPC = txtCodigoUPC;
    }

    public JComboBox<String> getCmbCategoriaProducto() {
        return cmbCategoriaProducto;
    }

    public void setCmbCategoriaProducto(JComboBox<String> cmbCategoriaProducto) {
        this.cmbCategoriaProducto = cmbCategoriaProducto;
    }

    public JComboBox<EnumSiNo> getCmbGarantia() {
        return cmbGarantia;
    }

    public void setCmbGarantia(JComboBox<EnumSiNo> cmbGarantia) {
        this.cmbGarantia = cmbGarantia;
    }

    public JTextField getTxtCantidad() {
        return txtCantidadEnsamble;
    }

    public void setTxtCantidad(JTextField txtCantidad) {
        this.txtCantidadEnsamble = txtCantidad;
    }

    public JTextField getTxtCantidadMinima() {
        return txtCantidadMinima;
    }

    public void setTxtCantidadMinima(JTextField txtCantidadMinima) {
        this.txtCantidadMinima = txtCantidadMinima;
    }

    public JTextArea getTxtCaracteristica() {
        return txtCaracteristica;
    }

    public void setTxtCaracteristica(JTextArea txtCaracteristica) {
        this.txtCaracteristica = txtCaracteristica;
    }

    public JTextField getTxtImagenProducto() {
        return txtImagenProducto;
    }

    public void setTxtImagenProducto(JTextField txtImagenProducto) {
        this.txtImagenProducto = txtImagenProducto;
    }

    public JTextField getTxtMarca() {
        return txtMarca;
    }

    public void setTxtMarca(JTextField txtMarca) {
        this.txtMarca = txtMarca;
    }

    public JTextArea getTxtObservaciones() {
        return txtObservaciones;
    }

    public void setTxtObservaciones(JTextArea txtObservaciones) {
        this.txtObservaciones = txtObservaciones;
    }

    public JTextField getTxtPrecioDistribuidor() {
        return txtPrecioDistribuidor;
    }

    public void setTxtPrecioDistribuidor(JTextField txtPrecioDistribuidor) {
        this.txtPrecioDistribuidor = txtPrecioDistribuidor;
    }

    public JTextField getTxtPrecioTarjeta() {
        return txtPrecioTarjeta;
    }

    public void setTxtPrecioTarjeta(JTextField txtPrecioTarjeta) {
        this.txtPrecioTarjeta = txtPrecioTarjeta;
    }

    public JTextField getTxtProducto() {
        return txtProductoEnsamble;
    }

    public void setTxtProducto(JTextField txtProducto) {
        this.txtProductoEnsamble = txtProducto;
    }

    public JTextField getTxtStockInicial() {
        return txtStockInicial;
    }

    public void setTxtStockInicial(JTextField txtStockInicial) {
        this.txtStockInicial = txtStockInicial;
    }

    public JTextField getTxtUbicacion() {
        return txtUbicacion;
    }

    public void setTxtUbicacion(JTextField txtUbicacion) {
        this.txtUbicacion = txtUbicacion;
    }

    public JButton getBtnAgregarEnsamble() {
        return btnAgregarEnsamble;
    }

    public void setBtnAgregarEnsamble(JButton btnAgregarEnsamble) {
        this.btnAgregarEnsamble = btnAgregarEnsamble;
    }

    public JButton getBtnBuscarProductoEnsamble() {
        return btnBuscarProductoEnsamble;
    }

    public void setBtnBuscarProductoEnsamble(JButton btnBuscarProductoEnsamble) {
        this.btnBuscarProductoEnsamble = btnBuscarProductoEnsamble;
    }

    public JButton getBtnEditarEnsamble() {
        return btnEditarEnsamble;
    }

    public void setBtnEditarEnsamble(JButton btnEditarEnsamble) {
        this.btnEditarEnsamble = btnEditarEnsamble;
    }

    public JButton getBtnEliminarEnsamble() {
        return btnEliminarEnsamble;
    }

    public void setBtnEliminarEnsamble(JButton btnEliminarEnsamble) {
        this.btnEliminarEnsamble = btnEliminarEnsamble;
    }

    public JTextField getTxtCantidadEnsamble() {
        return txtCantidadEnsamble;
    }

    public void setTxtCantidadEnsamble(JTextField txtCantidadEnsamble) {
        this.txtCantidadEnsamble = txtCantidadEnsamble;
    }

    public JTable getTblDatosEnsamble() {
        return tblDatosEnsamble;
    }

    public void setTblDatosEnsamble(JTable tblDatosEnsamble) {
        this.tblDatosEnsamble = tblDatosEnsamble;
    }

    public JTextField getTxtProductoEnsamble() {
        return txtProductoEnsamble;
    }

    public void setTxtProductoEnsamble(JTextField txtProductoEnsamble) {
        this.txtProductoEnsamble = txtProductoEnsamble;
    }
    
    
    
}
