/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.compra.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.corecodefaclite.util.CampoBuscarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author robert
 */
public abstract class CompraReporteProductoPanel extends ControladorCodefacInterface{

    /**
     * Creates new form CompraReporteProductoPanel
     */
    public CompraReporteProductoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtGenericoProductoProveedor = new javax.swing.JTextField();
        btnObtenerDatos = new javax.swing.JButton();
        chckTodos = new javax.swing.JCheckBox();
        btnBuscarGenerico = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInformacionReporte = new javax.swing.JTable();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte Producto/Proveedor");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        txtGenericoProductoProveedor.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtGenericoProductoProveedor, gridBagConstraints);

        btnObtenerDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/icon1.png"))); // NOI18N
        btnObtenerDatos.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        getContentPane().add(btnObtenerDatos, gridBagConstraints);

        chckTodos.setSelected(true);
        chckTodos.setText("Todos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(chckTodos, gridBagConstraints);

        btnBuscarGenerico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/Zoom.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnBuscarGenerico, gridBagConstraints);

        jScrollPane2.setViewportView(tblInformacionReporte);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        cmbTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione busqueda", "Producto", "Proveedor" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cmbTipoReporte, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Reporte:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        getContentPane().add(jLabel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarGenerico;
    private javax.swing.JButton btnObtenerDatos;
    private javax.swing.JCheckBox chckTodos;
    private javax.swing.JComboBox<String> cmbTipoReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInformacionReporte;
    private javax.swing.JTextField txtGenericoProductoProveedor;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBuscarGenerico() {
        return btnBuscarGenerico;
    }

    public void setBtnBuscarGenerico(JButton btnBuscarProducto) {
        this.btnBuscarGenerico = btnBuscarProducto;
    }

    public JButton getBtnObtenerDatos() {
        return btnObtenerDatos;
    }

    public void setBtnObtenerDatos(JButton btnObtenerDatos) {
        this.btnObtenerDatos = btnObtenerDatos;
    }

    public JCheckBox getChckTodos() {
        return chckTodos;
    }

    public void setChckTodos(JCheckBox chckTodos) {
        this.chckTodos = chckTodos;
    }
    
    @CampoBuscarAnotacion
    @LimpiarAnotacion
    public JTextField getTxtGenericoProductoProveedor() {
        return txtGenericoProductoProveedor;
    }

    public void setTxtGenericoProductoProveedor(JTextField txtProducto) {
        this.txtGenericoProductoProveedor = txtProducto;
    }

    public JComboBox<String> getCmbTipoReporte() {
        return cmbTipoReporte;
    }

    public void setCmbTipoReporte(JComboBox<String> cmbTipoReporte) {
        this.cmbTipoReporte = cmbTipoReporte;
    }

    public JTable getTblInformacionReporte() {
        return tblInformacionReporte;
    }

    public void setTblInformacionReporte(JTable tblInformacionReporte) {
        this.tblInformacionReporte = tblInformacionReporte;
    }
    
}
