/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.pos.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.vistas.core.TextFieldBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ButtonBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ComboBoxBinding;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.pos.Caja;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.pos.CajaPermiso;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.pos.CajaSession;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.CajaSessionEnum;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import javax.xml.ws.BindingType;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Robert
 */
public abstract class CajaSessionPanel extends ControladorCodefacInterface {

    /**
     * Creates new form CajaSessionPanel
     */
    public CajaSessionPanel() {
        initComponents();
        getPnlCierreCaja().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextValorApertura = new javax.swing.JTextField();
        jTextValorCierre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEstadoCierre = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jCmbCajaPermiso = new javax.swing.JComboBox<>();
        jTextFechaApertura = new javax.swing.JTextField();
        jTextHoraApertura = new javax.swing.JTextField();
        jTextFechaCierre = new javax.swing.JTextField();
        jTextHoraCierre = new javax.swing.JTextField();
        pnlCierreCaja = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbCajaSession = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Caja Sesión");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Fecha Apertura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Fecha Cierre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Hora Apertura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Hora Cierre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Valor Apertura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Valor Cierre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTextValorApertura, gridBagConstraints);

        jTextValorCierre.setInheritsPopupMenu(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTextValorCierre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("      ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jComboBoxEstadoCierre, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Caja:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jCmbCajaPermiso, gridBagConstraints);

        jTextFechaApertura.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTextFechaApertura, gridBagConstraints);

        jTextHoraApertura.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTextHoraApertura, gridBagConstraints);

        jTextFechaCierre.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTextFechaCierre, gridBagConstraints);

        jTextHoraCierre.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTextHoraCierre, gridBagConstraints);

        pnlCierreCaja.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCierreCaja.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Seleccioné la caja para realizar el cierre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCierreCaja.add(jLabel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCierreCaja.add(cmbCajaSession, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(pnlCierreCaja, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @ComboBoxBinding(source = "controlador.estadoCajaSessionList", valueSelect = "controlador.cajaSession.estadoCierreCaja")
    public JComboBox<CajaSessionEnum> getjComboBoxEstadoCierre() {
        return jComboBoxEstadoCierre;
    }

    public void setjComboBoxEstadoCierre(JComboBox<CajaSessionEnum> jComboBoxEstadoCierre) {
        this.jComboBoxEstadoCierre = jComboBoxEstadoCierre;
    }
   
    @LimpiarAnotacion 
    //@TextFieldBinding(value = "controlador.CajaSession.ValorApertura")
    public JTextField getjTextValorApertura() {
        return jTextValorApertura;
    }

    public void setjTextValorApertura(JTextField jTextValorApertura) {
        this.jTextValorApertura = jTextValorApertura;
    }

    @LimpiarAnotacion
    //@TextFieldBinding(value = "controlador.CajaSession.ValorCierre")
    public JTextField getjTextValorCierre() {
        return jTextValorCierre;
    }

    public void setjTextValorCierre(JTextField jTextValorCierre) {
        this.jTextValorCierre = jTextValorCierre;
    }

    public JTextField getjTextFechaApertura() {
        return jTextFechaApertura;
    }

    public void setjTextFechaApertura(JTextField jTextFechaApertura) {
        this.jTextFechaApertura = jTextFechaApertura;
    }

    public JTextField getjTextFechaCierre() {
        return jTextFechaCierre;
    }

    public void setjTextFechaCierre(JTextField jTextFechaCierre) {
        this.jTextFechaCierre = jTextFechaCierre;
    }

    public JTextField getjTextHoraApertura() {
        return jTextHoraApertura;
    }

    public void setjTextHoraApertura(JTextField jTextHoraApertura) {
        this.jTextHoraApertura = jTextHoraApertura;
    }

    public JTextField getjTextHoraCierre() {
        return jTextHoraCierre;
    }

    public void setjTextHoraCierre(JTextField jTextHoraCierre) {
        this.jTextHoraCierre = jTextHoraCierre;
    }

     
    @ComboBoxBinding(source = "controlador.cajasList",valueSelect = "controlador.CajaSession.Caja")
    public JComboBox<Caja> getjCmbCajaPermiso() {
        return jCmbCajaPermiso;
    }

    public void setjCmbCajaPermiso(JComboBox<Caja> jCmbCajaPermiso) {
        this.jCmbCajaPermiso = jCmbCajaPermiso;
    }   

    public JPanel getPnlCierreCaja() {
        return pnlCierreCaja;
    }

    public void setPnlCierreCaja(JPanel pnlCierreCaja) {
        this.pnlCierreCaja = pnlCierreCaja;
    }

    @ComboBoxBinding(source = "controlador.cajaSessionList",valueSelect = "controlador.cajaSessionSeleccionada")
    public JComboBox<CajaSession> getCmbCajaSession() {
        return cmbCajaSession;
    }

    public void setCmbCajaSession(JComboBox<CajaSession> cmbCajaSession) {
        this.cmbCajaSession = cmbCajaSession;
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<CajaSession> cmbCajaSession;
    private javax.swing.JComboBox<Caja> jCmbCajaPermiso;
    private javax.swing.JComboBox<CajaSessionEnum> jComboBoxEstadoCierre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFechaApertura;
    private javax.swing.JTextField jTextFechaCierre;
    private javax.swing.JTextField jTextHoraApertura;
    private javax.swing.JTextField jTextHoraCierre;
    private javax.swing.JTextField jTextValorApertura;
    private javax.swing.JTextField jTextValorCierre;
    private javax.swing.JPanel pnlCierreCaja;
    // End of variables declaration//GEN-END:variables
}
