/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.facturacion.panel;

import com.toedter.calendar.JDateChooser;
import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.corecodefaclite.ayuda.AyudaCodefacAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.Persona;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.DocumentoEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.TipoDocumentoEnum;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Carlos
 */
public abstract class FacturacionPanel extends ControladorCodefacInterface {

    /**
     * Creates new form FacturacionPanel
     */
    public FacturacionPanel() {
        initComponents();    
    }
    
   
    public JTextField getTxtValorTotal() {
        return txtValorTotal;
    }

    public JLabel getLblSubTotalDescuentoConImpuesto() {
        return lblSubTotalDescuentoConImpuesto;
    }

    public void setLblSubTotalDescuentoConImpuesto(JLabel lblSubTotalDescuentoConImpuesto) {
        this.lblSubTotalDescuentoConImpuesto = lblSubTotalDescuentoConImpuesto;
    }

    public JLabel getLblSubTotalDescuentoSinImpuesto() {
        return lblSubTotalDescuentoSinImpuesto;
    }

    public void setLblSubTotalDescuentoSinImpuesto(JLabel lblSubTotalDescuentoSinImpuesto) {
        this.lblSubTotalDescuentoSinImpuesto = lblSubTotalDescuentoSinImpuesto;
    }

    public void setTxtValorTotal(JTextField txtValorTotal) {
        this.txtValorTotal = txtValorTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel34 = new javax.swing.JLabel();
        PanelDetalleFactura = new javax.swing.JPanel();
        btnAgregarDetalleFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleFactura = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return colIndex != 0 && colIndex != 3 && colIndex != 4;
            }
        };
        jLabel40 = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnEditarDetalle = new javax.swing.JButton();
        btnQuitarDetalle = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        checkPorcentaje = new javax.swing.JCheckBox();
        jToolBar2 = new javax.swing.JToolBar();
        txtCodigoDetalle = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnCrearProducto = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        PanelFormasPago = new javax.swing.JPanel();
        btnAgregarFormaPago = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFormasPago = new javax.swing.JTable();
        btnQuitarDetalleFormaPago = new javax.swing.JButton();
        PanelDatosAdicionales = new javax.swing.JPanel();
        btnAgregarDatosAdicionales = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDatosAdicionales = new javax.swing.JTable();
        btnQuitarDatosAdicionales = new javax.swing.JButton();
        PanelValores = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblSubtotal12 = new javax.swing.JLabel();
        lblSubtotal0 = new javax.swing.JLabel();
        lblSubtotalNoObjetoDeIva = new javax.swing.JLabel();
        lblSubtotalExentoDeIva = new javax.swing.JLabel();
        lblSubtotalSinImpuesto = new javax.swing.JLabel();
        lblValorIce = new javax.swing.JLabel();
        lblIva12 = new javax.swing.JLabel();
        lblValorIRBPNR = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblPropina10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblTotalDescuento = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSubTotalDescuentoSinImpuesto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblSubTotalDescuentoConImpuesto = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        panelDatosFactura = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblSecuencial = new javax.swing.JLabel();
        jDateFechaEmision = new com.toedter.calendar.JDateChooser();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreComercial = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTelefonos = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblEstadoFactura = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cmbDocumento = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        panelTabDatos = new javax.swing.JTabbedPane();
        panelProductos = new javax.swing.JPanel();
        panelDatosEmpresa1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        btnBuscarEstudiante = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cmbRepresentante = new javax.swing.JComboBox<>();
        panelDatosPresupuestos = new javax.swing.JPanel();
        chkFiltroPresupuestoCliente = new javax.swing.JCheckBox();
        panelDatosEmpresa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblDireccionCliente = new javax.swing.JLabel();
        lblTelefonoCliente = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        txtCliente = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        lblEspacioBlanco = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel26.setText("jLabel26");

        jScrollPane4.setViewportView(jTextPane1);

        jLabel34.setText("jLabel34");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Factura");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/FacturaCeleste.png"))); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PanelDetalleFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Factura"));
        PanelDetalleFactura.setLayout(new java.awt.GridBagLayout());

        btnAgregarDetalleFactura.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(btnAgregarDetalleFactura, gridBagConstraints);

        tblDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetalleFactura);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PanelDetalleFactura.add(jScrollPane2, gridBagConstraints);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setText("Valor Unitario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        PanelDetalleFactura.add(jLabel40, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(txtValorUnitario, gridBagConstraints);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel41.setText("Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(jLabel41, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(txtCantidad, gridBagConstraints);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel42.setText("Descripcion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(jLabel42, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(txtDescripcion, gridBagConstraints);

        btnEditarDetalle.setText("Edit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(btnEditarDetalle, gridBagConstraints);

        btnQuitarDetalle.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(btnQuitarDetalle, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Descuento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        PanelDetalleFactura.add(jLabel19, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(txtDescuento, gridBagConstraints);

        checkPorcentaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        checkPorcentaje.setText("Porcentaje");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        PanelDetalleFactura.add(checkPorcentaje, gridBagConstraints);

        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);

        txtCodigoDetalle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jToolBar2.add(txtCodigoDetalle);

        btnAgregarProducto.setText("Producto");
        jToolBar2.add(btnAgregarProducto);

        btnCrearProducto.setText("+");
        jToolBar2.add(btnCrearProducto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelDetalleFactura.add(jToolBar2, gridBagConstraints);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel37.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        PanelDetalleFactura.add(jLabel37, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        getContentPane().add(PanelDetalleFactura, gridBagConstraints);

        PanelFormasPago.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Formas de Pago"), "Formas de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N
        PanelFormasPago.setLayout(new java.awt.GridBagLayout());

        btnAgregarFormaPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/add2.png"))); // NOI18N
        btnAgregarFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFormaPagoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        PanelFormasPago.add(btnAgregarFormaPago, gridBagConstraints);

        tblFormasPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblFormasPago);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PanelFormasPago.add(jScrollPane3, gridBagConstraints);

        btnQuitarDetalleFormaPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/cerrar-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        PanelFormasPago.add(btnQuitarDetalleFormaPago, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        getContentPane().add(PanelFormasPago, gridBagConstraints);

        PanelDatosAdicionales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Adicionales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N
        PanelDatosAdicionales.setLayout(new java.awt.GridBagLayout());

        btnAgregarDatosAdicionales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/add2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        PanelDatosAdicionales.add(btnAgregarDatosAdicionales, gridBagConstraints);

        tblDatosAdicionales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblDatosAdicionales);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PanelDatosAdicionales.add(jScrollPane5, gridBagConstraints);

        btnQuitarDatosAdicionales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/cerrar-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        PanelDatosAdicionales.add(btnQuitarDatosAdicionales, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        getContentPane().add(PanelDatosAdicionales, gridBagConstraints);

        PanelValores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelValores.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("SUBTOTAL SIN IMPUESTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("SUBTOTAL 12%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("SUBTOTAL 0%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("SUBTOTAL NO OBJETO IVA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("SUBTOTAL EXENTO IVA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel13, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("VALOR ICE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("IVA 12%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("VALOR IRBPNR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("PROPINA 10%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(jLabel18, gridBagConstraints);

        lblValorTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblValorTotal.setText("VALOR TOTAL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        PanelValores.add(lblValorTotal, gridBagConstraints);

        lblSubtotal12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubtotal12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotal12.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblSubtotal12, gridBagConstraints);

        lblSubtotal0.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubtotal0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotal0.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblSubtotal0, gridBagConstraints);

        lblSubtotalNoObjetoDeIva.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubtotalNoObjetoDeIva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalNoObjetoDeIva.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblSubtotalNoObjetoDeIva, gridBagConstraints);

        lblSubtotalExentoDeIva.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubtotalExentoDeIva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalExentoDeIva.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblSubtotalExentoDeIva, gridBagConstraints);

        lblSubtotalSinImpuesto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubtotalSinImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalSinImpuesto.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblSubtotalSinImpuesto, gridBagConstraints);

        lblValorIce.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblValorIce.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorIce.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblValorIce, gridBagConstraints);

        lblIva12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIva12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIva12.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblIva12, gridBagConstraints);

        lblValorIRBPNR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblValorIRBPNR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorIRBPNR.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblValorIRBPNR, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        PanelValores.add(jCheckBox1, gridBagConstraints);

        lblPropina10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPropina10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPropina10.setText("0.00");
        lblPropina10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 255), null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblPropina10, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("TOTAL DESCUENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        PanelValores.add(jLabel23, gridBagConstraints);

        lblTotalDescuento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotalDescuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalDescuento.setText("0.00");
        lblTotalDescuento.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 255), null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(lblTotalDescuento, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCUENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblSubTotalDescuentoSinImpuesto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubTotalDescuentoSinImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTotalDescuentoSinImpuesto.setText("0.00");
        lblSubTotalDescuentoSinImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        jPanel1.add(lblSubTotalDescuentoSinImpuesto, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("SUBTOTAL CON IMPUESTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        jPanel1.add(jLabel14, gridBagConstraints);

        lblSubTotalDescuentoConImpuesto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubTotalDescuentoConImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTotalDescuentoConImpuesto.setText("0.00");
        lblSubTotalDescuentoConImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(lblSubTotalDescuentoConImpuesto, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("SUBTOTAL SIN IMPUESTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        jPanel1.add(jLabel21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        PanelValores.add(jPanel1, gridBagConstraints);

        txtValorTotal.setColumns(5);
        txtValorTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtValorTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal.setText("0.00");
        txtValorTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        PanelValores.add(txtValorTotal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        getContentPane().add(PanelValores, gridBagConstraints);

        panelDatosFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Factura"));
        panelDatosFactura.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        panelDatosFactura.setLayout(new java.awt.GridBagLayout());

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setText("Secuencial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 5, 10);
        panelDatosFactura.add(jLabel35, gridBagConstraints);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel36.setText("Fecha Emision:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 5, 10);
        panelDatosFactura.add(jLabel36, gridBagConstraints);

        lblSecuencial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSecuencial.setText("001-002-9213912939");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 5, 10);
        panelDatosFactura.add(lblSecuencial, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 5, 10);
        panelDatosFactura.add(jDateFechaEmision, gridBagConstraints);

        jLabel38.setText("             ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelDatosFactura.add(jLabel38, gridBagConstraints);

        jLabel39.setText("             ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        panelDatosFactura.add(jLabel39, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelDatosFactura.add(jLabel22, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        panelDatosFactura.add(jLabel24, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Ruc:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        panelDatosFactura.add(jLabel1, gridBagConstraints);

        lblRuc.setBackground(new java.awt.Color(255, 255, 255));
        lblRuc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRuc.setText("Ruc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDatosFactura.add(lblRuc, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre Comercial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        panelDatosFactura.add(jLabel2, gridBagConstraints);

        lblNombreComercial.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreComercial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombreComercial.setText("Nombre Comercial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDatosFactura.add(lblNombreComercial, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Direccion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        panelDatosFactura.add(jLabel8, gridBagConstraints);

        lblDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lblDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDireccion.setText("direccion ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        panelDatosFactura.add(lblDireccion, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Telefonos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        panelDatosFactura.add(jLabel5, gridBagConstraints);

        lblTelefonos.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefonos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTelefonos.setText("telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDatosFactura.add(lblTelefonos, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        panelDatosFactura.add(jLabel25, gridBagConstraints);

        lblEstadoFactura.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblEstadoFactura.setText("Procesando");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelDatosFactura.add(lblEstadoFactura, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 5, 10);
        panelDatosFactura.add(jLabel27, gridBagConstraints);

        cmbDocumento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 5, 10);
        panelDatosFactura.add(cmbDocumento, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Tipo Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 10);
        panelDatosFactura.add(jLabel28, gridBagConstraints);

        cmbTipoDocumento.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 5, 10);
        panelDatosFactura.add(cmbTipoDocumento, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        getContentPane().add(panelDatosFactura, gridBagConstraints);

        panelTabDatos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelTabDatos.addTab("Producto", panelProductos);

        panelDatosEmpresa1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        panelDatosEmpresa1.setLayout(new java.awt.GridBagLayout());

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Representante:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        panelDatosEmpresa1.add(jLabel30, gridBagConstraints);

        txtEstudiante.setEditable(false);
        txtEstudiante.setText("                                       ...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelDatosEmpresa1.add(txtEstudiante, gridBagConstraints);

        btnBuscarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelDatosEmpresa1.add(btnBuscarEstudiante, gridBagConstraints);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel32.setText("Estudiante:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        panelDatosEmpresa1.add(jLabel32, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        panelDatosEmpresa1.add(jLabel33, gridBagConstraints);

        cmbRepresentante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelDatosEmpresa1.add(cmbRepresentante, gridBagConstraints);

        panelTabDatos.addTab("Académico", panelDatosEmpresa1);

        panelDatosPresupuestos.setLayout(new java.awt.GridBagLayout());

        chkFiltroPresupuestoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chkFiltroPresupuestoCliente.setText("filtrar presupuesto por cliente");
        chkFiltroPresupuestoCliente.setToolTipText("Permite filtrar presupuesto solo pertenecientes al cliente seleccionado para la factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDatosPresupuestos.add(chkFiltroPresupuestoCliente, gridBagConstraints);

        panelTabDatos.addTab("Presupuestos", panelDatosPresupuestos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        getContentPane().add(panelTabDatos, gridBagConstraints);

        panelDatosEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N
        panelDatosEmpresa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        panelDatosEmpresa.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Direccion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panelDatosEmpresa.add(jLabel3, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panelDatosEmpresa.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Telefono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panelDatosEmpresa.add(jLabel7, gridBagConstraints);

        lblNombreCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombreCliente.setText("nombre cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panelDatosEmpresa.add(lblNombreCliente, gridBagConstraints);

        lblDireccionCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDireccionCliente.setText("direccion cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panelDatosEmpresa.add(lblDireccionCliente, gridBagConstraints);

        lblTelefonoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTelefonoCliente.setText("Telefono Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panelDatosEmpresa.add(lblTelefonoCliente, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        panelDatosEmpresa.add(jLabel20, gridBagConstraints);

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtCliente.setColumns(15);
        txtCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToolBar1.add(txtCliente);

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/mas-ico.png"))); // NOI18N
        btnAgregarCliente.setText("Agregar");
        jToolBar1.add(btnAgregarCliente);

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        btnBuscarCliente.setToolTipText("Buscar Cliente");
        jToolBar1.add(btnBuscarCliente);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 20, 3, 20);
        panelDatosEmpresa.add(jToolBar1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        panelDatosEmpresa.add(lblEspacioBlanco, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        getContentPane().add(panelDatosEmpresa, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBox getCheckPorcentaje() {
        return checkPorcentaje;
    }

    public void setCheckPorcentaje(JCheckBox checkPorcentaje) {
        this.checkPorcentaje = checkPorcentaje;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=false ,expresionRegular = "^[0-9]+([.][0-9]+)?$",nombre = "Descuento")
    public JTextField getTxtDescuento() {
        return txtDescuento;
    }

    public void setTxtDescuento(JTextField txtDescuento) {
        this.txtDescuento = txtDescuento;
    }

    private void btnAgregarFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFormaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarFormaPagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatosAdicionales;
    private javax.swing.JPanel PanelDetalleFactura;
    private javax.swing.JPanel PanelFormasPago;
    private javax.swing.JPanel PanelValores;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarDatosAdicionales;
    private javax.swing.JButton btnAgregarDetalleFactura;
    private javax.swing.JButton btnAgregarFormaPago;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnEditarDetalle;
    private javax.swing.JButton btnQuitarDatosAdicionales;
    private javax.swing.JButton btnQuitarDetalle;
    private javax.swing.JButton btnQuitarDetalleFormaPago;
    private javax.swing.JCheckBox checkPorcentaje;
    private javax.swing.JCheckBox chkFiltroPresupuestoCliente;
    private javax.swing.JComboBox<DocumentoEnum> cmbDocumento;
    private javax.swing.JComboBox<Persona> cmbRepresentante;
    private javax.swing.JComboBox<TipoDocumentoEnum> cmbTipoDocumento;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateFechaEmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblEspacioBlanco;
    private javax.swing.JLabel lblEstadoFactura;
    private javax.swing.JLabel lblIva12;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreComercial;
    private javax.swing.JLabel lblPropina10;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblSecuencial;
    private javax.swing.JLabel lblSubTotalDescuentoConImpuesto;
    private javax.swing.JLabel lblSubTotalDescuentoSinImpuesto;
    private javax.swing.JLabel lblSubtotal0;
    private javax.swing.JLabel lblSubtotal12;
    private javax.swing.JLabel lblSubtotalExentoDeIva;
    private javax.swing.JLabel lblSubtotalNoObjetoDeIva;
    private javax.swing.JLabel lblSubtotalSinImpuesto;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblTelefonos;
    private javax.swing.JLabel lblTotalDescuento;
    private javax.swing.JLabel lblValorIRBPNR;
    private javax.swing.JLabel lblValorIce;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel panelDatosEmpresa;
    private javax.swing.JPanel panelDatosEmpresa1;
    private javax.swing.JPanel panelDatosFactura;
    private javax.swing.JPanel panelDatosPresupuestos;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JTabbedPane panelTabDatos;
    private javax.swing.JTable tblDatosAdicionales;
    private javax.swing.JTable tblDetalleFactura;
    private javax.swing.JTable tblFormasPago;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigoDetalle;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtEstudiante;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarCliente() {
        return btnAgregarCliente;
    }

    public void setBtnAgregarCliente(JButton bntAgregarCliente) {
        this.btnAgregarCliente = bntAgregarCliente;
    }

    public JButton getBtnBuscarCliente() {
        return btnBuscarCliente;
    }

    public void setBtnBuscarCliente(JButton btnBuscarCliente) {
        this.btnBuscarCliente = btnBuscarCliente;
    }

    public JLabel getLblDireccionCliente() {
        return lblDireccionCliente;
    }

    public JLabel getLblNombreCliente() {
        return lblNombreCliente;
    }

    public JLabel getLblTelefonoCliente() {
        return lblTelefonoCliente;
    }

    public JTextField getTxtCliente() {
        return txtCliente;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public JLabel getLblNombreComercial() {
        return lblNombreComercial;
    }

    public JLabel getLblRuc() {
        return lblRuc;
    }

    public JLabel getLblTelefonos() {
        return lblTelefonos;
    }

    public JButton getBtnAgregarFormaPago() {
        return btnAgregarFormaPago;
    }

    public void setBtnAgregarFormaPago(JButton btnAgregarFormaPago) {
        this.btnAgregarFormaPago = btnAgregarFormaPago;
    }

    public JTable getTblFormasPago() {
        return tblFormasPago;
    }

    public void setTblFormasPago(JTable tblFormasPago) {
        this.tblFormasPago = tblFormasPago;
    }

    public JButton getBtnAgregarDetalleFactura() {
        return btnAgregarDetalleFactura;
    }

    public void setBtnAgregarDetalleFactura(JButton btnAgregarDetalleFactura) {
        this.btnAgregarDetalleFactura = btnAgregarDetalleFactura;
    }

    public JTable getTblDetalleFactura() {
        return tblDetalleFactura;
    }

    public void setTblDetalleFactura(JTable tblDetalleFactura) {
        this.tblDetalleFactura = tblDetalleFactura;
    }

    public JButton getBtnAgregarProducto() {
        return btnAgregarProducto;
    }

    public void setBtnAgregarProducto(JButton btnAgregarProducto) {
        this.btnAgregarProducto = btnAgregarProducto;
    }

    public JButton getBtnEditarDetalle() {
        return btnEditarDetalle;
    }

    public void setBtnEditarDetalle(JButton btnEditarDetalle) {
        this.btnEditarDetalle = btnEditarDetalle;
    }

    public JButton getBtnQuitarDetalle() {
        return btnQuitarDetalle;
    }

    public void setBtnQuitarDetalle(JButton btnQuitarDetalle) {
        this.btnQuitarDetalle = btnQuitarDetalle;
    }
    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true ,expresionRegular = "^[0-9]+$",nombre = "Cantidad",grupo = "detalles")
    public JTextField getTxtCantidad() {
        return txtCantidad;
    }

    public void setTxtCantidad(JTextField txtCantidad) {
        this.txtCantidad = txtCantidad;
    }
    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true ,expresionRegular = "^[A-Za-z0-9\\s.\\_\\-\\ ]*$",nombre = "Descripcion",grupo = "detalles")
    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public JButton getBtnQuitarDetalleFormaPago() {
        return btnQuitarDetalleFormaPago;
    }

    public void setBtnQuitarDetalleFormaPago(JButton btnQuitarFormaPago) {
        this.btnQuitarDetalleFormaPago = btnQuitarFormaPago;
    }

    public void setTxtDescripcion(JTextField txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }
    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true ,expresionRegular = "^[0-9]+([.][0-9]+)?$",nombre = "Valor Unitario",grupo = "detalles")
    public JTextField getTxtValorUnitario() {
        return txtValorUnitario;
    }

    public JLabel getLblSubtotalExentoDeIva() {
        return lblSubtotalExentoDeIva;
    }

    public void setLblSubtotalExentoDeIva(JLabel lblSubtotalExentoDeIva) {
        this.lblSubtotalExentoDeIva = lblSubtotalExentoDeIva;
    }

    public void setTxtValorUnitario(JTextField txtValorUnitario) {
        this.txtValorUnitario = txtValorUnitario;
    }

    public JLabel getLblIva12() {
        return lblIva12;
    }

    public void setLblIva12(JLabel lblIva12) {
        this.lblIva12 = lblIva12;
    }

    public JLabel getLblPropina10() {
        return lblPropina10;
    }

    public void setLblPropina10(JLabel lblPropina10) {
        this.lblPropina10 = lblPropina10;
    }

    public JLabel getLblSubtotal0() {
        return lblSubtotal0;
    }

    public void setLblSubtotal0(JLabel lblSubtotal0) {
        this.lblSubtotal0 = lblSubtotal0;
    }

    public JLabel getLblSubtotal12() {
        return lblSubtotal12;
    }

    public void setLblSubtotal12(JLabel lblSubtotal12) {
        this.lblSubtotal12 = lblSubtotal12;
    }

    public JLabel getLblSubtotalNoObjetoDeIva() {
        return lblSubtotalNoObjetoDeIva;
    }

    public void setLblSubtotalNoObjetoDeIva(JLabel lblSubtotalNoObjetoDeIva) {
        this.lblSubtotalNoObjetoDeIva = lblSubtotalNoObjetoDeIva;
    }

    public JLabel getLblSubtotalSinImpuesto() {
        return lblSubtotalSinImpuesto;
    }

    public void setLblSubtotalSinImpuesto(JLabel lblSubtotalSinImpuesto) {
        this.lblSubtotalSinImpuesto = lblSubtotalSinImpuesto;
    }
    
    public JLabel getLblTotalDescuento() {
        return lblTotalDescuento;
    }

    public void setLblTotalDescuento(JLabel lblTotalDescuento) {
        this.lblTotalDescuento = lblTotalDescuento;
    }

    public JLabel getLblValorIRBPNR() {
        return lblValorIRBPNR;
    }

    public void setLblValorIRBPNR(JLabel lblValorIRBPNR) {
        this.lblValorIRBPNR = lblValorIRBPNR;
    }

    public JLabel getLblValorIce() {
        return lblValorIce;
    }

    public void setLblValorIce(JLabel lblValorIce) {
        this.lblValorIce = lblValorIce;
    }

    public JLabel getLblValorTotal() {
        return lblValorTotal;
    }

    public void setLblValorTotal(JLabel lblValorTotal) {
        this.lblValorTotal = lblValorTotal;
    }

    public JTable getTblDatosAdicionales() {
        return tblDatosAdicionales;
    }

    public void setTblDatosAdicionales(JTable tblDatosAdicionales) {
        this.tblDatosAdicionales = tblDatosAdicionales;
    }

    public JButton getBtnCrearProducto() {
        return btnCrearProducto;
    }

    public void setBtnCrearProducto(JButton btnCrearProducto) {
        this.btnCrearProducto = btnCrearProducto;
    }

    public JLabel getLblSecuencial() {
        return lblSecuencial;
    }

    public void setLblSecuencial(JLabel lblSecuencial) {
        this.lblSecuencial = lblSecuencial;
    }

    public JDateChooser getjDateFechaEmision() {
        return jDateFechaEmision;
    }

    public void setjDateFechaEmision(JDateChooser jDateFechaEmision) {
        this.jDateFechaEmision = jDateFechaEmision;
    }

    public JLabel getLblEstadoFactura() {
        return lblEstadoFactura;
    }

    public void setLblEstadoFactura(JLabel lblEstadoFactura) {
        this.lblEstadoFactura = lblEstadoFactura;
    }

    public JComboBox<DocumentoEnum> getCmbDocumento() {
        return cmbDocumento;
    }

    public void setCmbDocumento(JComboBox<DocumentoEnum> cmbDocumento) {
        this.cmbDocumento = cmbDocumento;
    }

    public JComboBox<TipoDocumentoEnum> getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public void setCmbTipoDocumento(JComboBox<TipoDocumentoEnum> cmbTipoDocumento) {
        this.cmbTipoDocumento = cmbTipoDocumento;
    }

    public JTabbedPane getPanelTabDatos() {
        return panelTabDatos;
    }

    public void setPanelTabDatos(JTabbedPane panelTabDatos) {
        this.panelTabDatos = panelTabDatos;
    }

    public JButton getBtnBuscarEstudiante() {
        return btnBuscarEstudiante;
    }

    public void setBtnBuscarEstudiante(JButton btnBuscarEstudiante) {
        this.btnBuscarEstudiante = btnBuscarEstudiante;
    }


    public JTextField getTxtEstudiante() {
        return txtEstudiante;
    }

    public void setTxtEstudiante(JTextField txtEstudiante) {
        this.txtEstudiante = txtEstudiante;
    }

    public JButton getBtnAgregarDatosAdicionales() {
        return btnAgregarDatosAdicionales;
    }

    public void setBtnAgregarDatosAdicionales(JButton btnAgregarDatosAdicionales) {
        this.btnAgregarDatosAdicionales = btnAgregarDatosAdicionales;
    }


    public JComboBox<Persona> getCmbRepresentante() {
        return cmbRepresentante;
    }

    public void setCmbRepresentante(JComboBox<Persona> cmbRepresentante) {
        this.cmbRepresentante = cmbRepresentante;
    }


    public JCheckBox getChkFiltroPresupuestoCliente() {
        return chkFiltroPresupuestoCliente;
    }

    public JTextField getTxtCodigoDetalle() {
        return txtCodigoDetalle;
    }

    public void setTxtCodigoDetalle(JTextField txtCodigoDetalle) {
        this.txtCodigoDetalle = txtCodigoDetalle;
    }
    
    
}
