/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.gestionacademica.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.Periodo;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Carlos
 */
public abstract class DeudaPorRubroPanel extends ControladorCodefacInterface {

    /**
     * Creates new form DeudaPorRubroPanel
     */
    public DeudaPorRubroPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRubro = new javax.swing.JTextField();
        btnBuscarRubro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        chkSeleccionarTodos = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnAgregarEstudiante = new javax.swing.JButton();
        btnEliminarRubro = new javax.swing.JButton();
        lblEspacio1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Deudas por Rubro");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Rubro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtRubro.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtRubro, gridBagConstraints);

        btnBuscarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        btnBuscarRubro.setToolTipText("BuscarRubro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnBuscarRubro, gridBagConstraints);

        jLabel2.setText("Periodo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbPeriodo, gridBagConstraints);

        jScrollPane1.setViewportView(tblDetalles);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        chkSeleccionarTodos.setText("Seleccion Todo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(chkSeleccionarTodos, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jPanel2, gridBagConstraints);

        jToolBar2.setBorder(null);

        btnAgregarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/32Pixeles/Agregar.png"))); // NOI18N
        btnAgregarEstudiante.setToolTipText("Agregar Estudiante");
        btnAgregarEstudiante.setFocusable(false);
        btnAgregarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnAgregarEstudiante);

        btnEliminarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/delete-icon.png"))); // NOI18N
        btnEliminarRubro.setToolTipText("Quitar Estudiantes");
        btnEliminarRubro.setFocusable(false);
        btnEliminarRubro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarRubro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnEliminarRubro);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jToolBar2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        jPanel1.add(lblEspacio1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstudiante;
    private javax.swing.JButton btnBuscarRubro;
    private javax.swing.JButton btnEliminarRubro;
    private javax.swing.JCheckBox chkSeleccionarTodos;
    private javax.swing.JComboBox<Periodo> cmbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTextField txtRubro;
    // End of variables declaration//GEN-END:variables

    public JComboBox<Periodo> getCmbPeriodo() {
        return cmbPeriodo;
    }

    public void setCmbPeriodo(JComboBox<Periodo> cmbPeriodo) {
        this.cmbPeriodo = cmbPeriodo;
    }

    public JButton getBtnBuscarRubro() {
        return btnBuscarRubro;
    }

    public void setBtnBuscarRubro(JButton btnBuscarRubro) {
        this.btnBuscarRubro = btnBuscarRubro;
    }

    public JTextField getTxtRubro() {
        return txtRubro;
    }

    public void setTxtRubro(JTextField txtRubro) {
        this.txtRubro = txtRubro;
    }

    public JTable getTblDetalles() {
        return tblDetalles;
    }

    public void setTblDetalles(JTable tblDetalles) {
        this.tblDetalles = tblDetalles;
    }

    public JCheckBox getChkSeleccionarTodos() {
        return chkSeleccionarTodos;
    }

    public void setChkSeleccionarTodos(JCheckBox chkSeleccionarTodos) {
        this.chkSeleccionarTodos = chkSeleccionarTodos;
    }

    public JButton getBtnAgregarEstudiante() {
        return btnAgregarEstudiante;
    }

    public void setBtnAgregarEstudiante(JButton btnAgregarEstudiante) {
        this.btnAgregarEstudiante = btnAgregarEstudiante;
    }

    public JButton getBtnEliminarRubro() {
        return btnEliminarRubro;
    }

    public void setBtnEliminarRubro(JButton btnEliminarRubro) {
        this.btnEliminarRubro = btnEliminarRubro;
    }

    
    

    
}
