/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.gestionacademica.panel;

import com.toedter.calendar.JDateChooser;
import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.Nacionalidad;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.EnumSiNo;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.GeneralEnumEstado;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.GeneroEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.TipoDiscapacidadEnum;
import ec.com.codesoft.codefaclite.utilidades.validadores.ExpresionRegular;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Carlos
 */
public abstract class EstudiantePanel extends ControladorCodefacInterface {

    public static final String NOMBRE_VALIDADOR_IDENTIFICACION = "Identificacion";

    /**
     * Creates new form Estudiante
     */
    public EstudiantePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblCodSistema = new javax.swing.JLabel();
        lblCodAuxiliar = new javax.swing.JLabel();
        txtCodAuxiliar = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        lblFechaNacimiento = new javax.swing.JLabel();
        dateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        cmbNacionalidad = new javax.swing.JComboBox<>();
        cmbEtnia = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        lblEtnia = new javax.swing.JLabel();
        lblNacionalidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblEspacio = new javax.swing.JLabel();
        lblCodigoSistema = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblRepresentante = new javax.swing.JLabel();
        txtRepresentante = new javax.swing.JTextField();
        btnBuscarRepresentante = new javax.swing.JButton();
        btnAgregarRepresentante = new javax.swing.JButton();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblFacturarANombre = new javax.swing.JLabel();
        txtFacturarANombre = new javax.swing.JTextField();
        btnBuscarPersonaFacturar = new javax.swing.JButton();
        btnAgregarPersonaFacturar = new javax.swing.JButton();
        lblAdicionales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdicionales = new javax.swing.JTextArea();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDiscapacidad = new javax.swing.JLabel();
        cmbDiscapacidad = new javax.swing.JComboBox<>();
        lblConadis = new javax.swing.JLabel();
        txtConadis = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cmbTipoDiscapacidad = new javax.swing.JComboBox<>();
        lblPorcentaje = new javax.swing.JLabel();
        txtPorcentajeDiscapacidad = new javax.swing.JTextField();
        lblObservaciones = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObsDiscapacidad = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Estudiante");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblCodSistema.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCodSistema.setText("Codigo Sistema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblCodSistema, gridBagConstraints);

        lblCodAuxiliar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCodAuxiliar.setText("Codigo Auxiliar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblCodAuxiliar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtCodAuxiliar, gridBagConstraints);

        lblCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCedula.setText("Cédula:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblCedula, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtCedula, gridBagConstraints);

        lblCorreo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCorreo.setText("Correo electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblCorreo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtCorreo, gridBagConstraints);

        lblNombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombres.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblNombres, gridBagConstraints);

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtNombres, gridBagConstraints);

        lblApellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblApellidos.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblApellidos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtApellidos, gridBagConstraints);

        lblGenero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblGenero.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblGenero, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(cmbGenero, gridBagConstraints);

        lblFechaNacimiento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFechaNacimiento.setText("Fecha nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblFechaNacimiento, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(dateFechaNacimiento, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(cmbNacionalidad, gridBagConstraints);

        cmbEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mestizos", "Montubios", "Afroecuatorianos", "Indígenas", "Blancos", "Otros" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(cmbEtnia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(cmbEstado, gridBagConstraints);

        lblEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEstado.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblEstado, gridBagConstraints);

        lblEtnia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEtnia.setText("Etnia: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblEtnia, gridBagConstraints);

        lblNacionalidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNacionalidad.setText("Nacionalidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel1.add(lblNacionalidad, gridBagConstraints);

        jLabel1.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel10.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel1.add(jLabel11, gridBagConstraints);

        jLabel12.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel1.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(lblEspacio, gridBagConstraints);

        lblCodigoSistema.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodigoSistema.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblCodigoSistema, gridBagConstraints);

        jTabbedPane1.addTab("Datos Generales", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblRepresentante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRepresentante.setText("Representante:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel2.add(lblRepresentante, gridBagConstraints);

        txtRepresentante.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(txtRepresentante, gridBagConstraints);

        btnBuscarRepresentante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(btnBuscarRepresentante, gridBagConstraints);

        btnAgregarRepresentante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/add_user.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(btnAgregarRepresentante, gridBagConstraints);

        lblCelular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCelular.setText("Celular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel2.add(lblCelular, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(txtCelular, gridBagConstraints);

        lblFacturarANombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFacturarANombre.setText("Representante 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel2.add(lblFacturarANombre, gridBagConstraints);

        txtFacturarANombre.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(txtFacturarANombre, gridBagConstraints);

        btnBuscarPersonaFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel2.add(btnBuscarPersonaFacturar, gridBagConstraints);

        btnAgregarPersonaFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/persona-ico.png"))); // NOI18N
        btnAgregarPersonaFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonaFacturarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel2.add(btnAgregarPersonaFacturar, gridBagConstraints);

        lblAdicionales.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAdicionales.setText("Datos Adicionales:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel2.add(lblAdicionales, gridBagConstraints);

        txtAdicionales.setColumns(20);
        txtAdicionales.setRows(5);
        jScrollPane1.setViewportView(txtAdicionales);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        lblTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTelefono.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel2.add(lblTelefono, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(txtTelefono, gridBagConstraints);

        lblDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDireccion.setText("Direccion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel2.add(lblDireccion, gridBagConstraints);

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane2.setViewportView(txtDireccion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        jLabel3.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel7.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel9, gridBagConstraints);

        jLabel16.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel2.add(jLabel16, gridBagConstraints);

        jTabbedPane1.addTab("Datos Secundarios", jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        lblDiscapacidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDiscapacidad.setText("Discapacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel3.add(lblDiscapacidad, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel3.add(cmbDiscapacidad, gridBagConstraints);

        lblConadis.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblConadis.setText("Conadis:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel3.add(lblConadis, gridBagConstraints);

        txtConadis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConadisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel3.add(txtConadis, gridBagConstraints);

        lblTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTipo.setText("Tipo discapacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel3.add(lblTipo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel3.add(cmbTipoDiscapacidad, gridBagConstraints);

        lblPorcentaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPorcentaje.setText("Porcentaje discapacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel3.add(lblPorcentaje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel3.add(txtPorcentajeDiscapacidad, gridBagConstraints);

        lblObservaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblObservaciones.setText("Observaciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel3.add(lblObservaciones, gridBagConstraints);

        txtObsDiscapacidad.setColumns(20);
        txtObsDiscapacidad.setRows(5);
        jScrollPane3.setViewportView(txtObsDiscapacidad);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel3.add(jScrollPane3, gridBagConstraints);

        jLabel5.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel13.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel3.add(jLabel13, gridBagConstraints);

        jLabel14.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel3.add(jLabel14, gridBagConstraints);

        jLabel15.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        jPanel3.add(jLabel15, gridBagConstraints);

        jTabbedPane1.addTab("Discapacidad", jPanel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtConadisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConadisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConadisActionPerformed

    private void btnAgregarPersonaFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonaFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPersonaFacturarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersonaFacturar;
    private javax.swing.JButton btnAgregarRepresentante;
    private javax.swing.JButton btnBuscarPersonaFacturar;
    private javax.swing.JButton btnBuscarRepresentante;
    private javax.swing.JComboBox<EnumSiNo> cmbDiscapacidad;
    private javax.swing.JComboBox<GeneralEnumEstado> cmbEstado;
    private javax.swing.JComboBox<String> cmbEtnia;
    private javax.swing.JComboBox<GeneroEnum> cmbGenero;
    private javax.swing.JComboBox<Nacionalidad> cmbNacionalidad;
    private javax.swing.JComboBox<TipoDiscapacidadEnum> cmbTipoDiscapacidad;
    private com.toedter.calendar.JDateChooser dateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdicionales;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCodAuxiliar;
    private javax.swing.JLabel lblCodSistema;
    private javax.swing.JLabel lblCodigoSistema;
    private javax.swing.JLabel lblConadis;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDiscapacidad;
    private javax.swing.JLabel lblEspacio;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEtnia;
    private javax.swing.JLabel lblFacturarANombre;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblRepresentante;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextArea txtAdicionales;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodAuxiliar;
    private javax.swing.JTextField txtConadis;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtFacturarANombre;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextArea txtObsDiscapacidad;
    private javax.swing.JTextField txtPorcentajeDiscapacidad;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public JComboBox<GeneroEnum> getCmbGenero() {
        return cmbGenero;
    }

    public void setCmbGenero(JComboBox<GeneroEnum> cmbGenero) {
        this.cmbGenero = cmbGenero;
    }

    public JDateChooser getDateFechaNacimiento() {
        return dateFechaNacimiento;
    }

    public void setDateFechaNacimiento(JDateChooser dateFechaNacimiento) {
        this.dateFechaNacimiento = dateFechaNacimiento;
    }

    @LimpiarAnotacion
    public JTextArea getTxtAdicionales() {
        return txtAdicionales;
    }

    public void setTxtAdicionales(JTextArea txtAdicionales) {
        this.txtAdicionales = txtAdicionales;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[a-zA-ñÑáéíóúÁÉÍÓÚ\\s0-9.\\_\\-]*$", nombre = "Apellidos", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTxtApellidos() {
        return txtApellidos;
    }

    public void setTxtApellidos(JTextField txtApellidos) {
        this.txtApellidos = txtApellidos;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, personalizado = {"validarIdentificacionSegunOpcionEstablecida"}, min = 0, max = 13, expresionRegular = "", nombre = NOMBRE_VALIDADOR_IDENTIFICACION)
    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public void setTxtCedula(JTextField txtCedula) {
        this.txtCedula = txtCedula;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[0][0-9]{9}$", nombre = "Celular", expresionRegularMensaje = "Ingrese un número de celular valido")
    public JTextField getTxtCelular() {
        return txtCelular;
    }

    public void setTxtCelular(JTextField txtCelular) {
        this.txtCelular = txtCelular;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$", nombre = "Codigo Auxiliar", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTxtCodAuxiliar() {
        return txtCodAuxiliar;
    }

    public void setTxtCodAuxiliar(JTextField txtCodAuxiliar) {
        this.txtCodAuxiliar = txtCodAuxiliar;
    }


    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[a-zA-ñÑáéíóúÁÉÍÓÚ\\s0-9.\\_\\-]*$", nombre = "Nombre", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTxtNombres() {
        return txtNombres;
    }

    public void setTxtNombres(JTextField txtNombres) {
        this.txtNombres = txtNombres;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, min = 0, expresionRegular = "^[A-Za-z0-9\\s.\\_\\-\\,\\ ]*$", nombre = "Direccion", expresionRegularMensaje = "No se permite la letra ñ, ni tildes")
    public JTextArea getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextArea txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    @LimpiarAnotacion
    public JTextField getTxtRepresentante() {
        return txtRepresentante;
    }

    public void setTxtRepresentante(JTextField txtRepresentante) {
        this.txtRepresentante = txtRepresentante;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[0][0-9]{8}$", nombre = "Telefono", expresionRegularMensaje = "Anteponga el código provincial")
    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public JComboBox<GeneralEnumEstado> getCmbEstado() {
        return cmbEstado;
    }

    public void setCmbEstado(JComboBox<GeneralEnumEstado> cmbEstado) {
        this.cmbEstado = cmbEstado;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$", nombre = "Correo Electronico", expresionRegularMensaje = "Ingrese una dirección de correo valida")
    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JButton getBtnBuscarRepresentante() {
        return btnBuscarRepresentante;
    }

    public void setBtnBuscarRepresentante(JButton btnBuscarRepresentante) {
        this.btnBuscarRepresentante = btnBuscarRepresentante;
    }

    public JButton getBtnAgregarRepresentante() {
        return btnAgregarRepresentante;
    }

    public void setBtnAgregarRepresentante(JButton btnAgregarRepresentante) {
        this.btnAgregarRepresentante = btnAgregarRepresentante;
    }

    public JComboBox<EnumSiNo> getCmbDiscapacidad() {
        return cmbDiscapacidad;
    }

    public void setCmbDiscapacidad(JComboBox<EnumSiNo> cmbDiscapacidad) {
        this.cmbDiscapacidad = cmbDiscapacidad;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, min = 0, max = 10, expresionRegular = "^[A-Za-z0-9\\s.\\_\\-\\,\\ ]*$", nombre = "Conadis", expresionRegularMensaje = "No se permite la letra ñ, ni tildes")
    public JTextField getTxtConadis() {
        return txtConadis;
    }

    public void setTxtConadis(JTextField txtConadis) {
        this.txtConadis = txtConadis;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = ExpresionRegular.soloNumeros, nombre = "Porcentaje", expresionRegularMensaje = "Solo se permite numeros enteros positivos")
    public JTextField getTxtPorcentajeDiscapacidad() {
        return txtPorcentajeDiscapacidad;
    }

    public void setTxtPorcentajeDiscapacidad(JTextField txtPorcentajeDiscapacidad) {
        this.txtPorcentajeDiscapacidad = txtPorcentajeDiscapacidad;
    }

    public JComboBox<Nacionalidad> getCmbNacionalidad() {
        return cmbNacionalidad;
    }

    public void setCmbNacionalidad(JComboBox<Nacionalidad> cmbNacionalidad) {
        this.cmbNacionalidad = cmbNacionalidad;
    }

    public JComboBox<TipoDiscapacidadEnum> getCmbTipoDiscapacidad() {
        return cmbTipoDiscapacidad;
    }

    public void setCmbTipoDiscapacidad(JComboBox<TipoDiscapacidadEnum> cmbTipoDiscapacidad) {
        this.cmbTipoDiscapacidad = cmbTipoDiscapacidad;
    }

    @LimpiarAnotacion
    public JTextArea getTxtObsDiscapacidad() {
        return txtObsDiscapacidad;
    }

    public void setTxtObsDiscapacidad(JTextArea txtObsDiscapacidad) {
        this.txtObsDiscapacidad = txtObsDiscapacidad;
    }

    public JButton getBtnAgregarPersonaFacturar() {
        return btnAgregarPersonaFacturar;
    }

    public void setBtnAgregarPersonaFacturar(JButton btnAgregarPersonaFacturar) {
        this.btnAgregarPersonaFacturar = btnAgregarPersonaFacturar;
    }

    public JButton getBtnBuscarPersonaFacturar() {
        return btnBuscarPersonaFacturar;
    }

    public void setBtnBuscarPersonaFacturar(JButton btnBuscarPersonaFacturar) {
        this.btnBuscarPersonaFacturar = btnBuscarPersonaFacturar;
    }

    public JComboBox<String> getCmbEtnia() {
        return cmbEtnia;
    }

    public void setCmbEtnia(JComboBox<String> cmbEtnia) {
        this.cmbEtnia = cmbEtnia;
    }
    
    @LimpiarAnotacion
    public JTextField getTxtFacturarANombre() {
        return txtFacturarANombre;
    }

    public void setTxtFacturarANombre(JTextField txtFacturarANombre) {
        this.txtFacturarANombre = txtFacturarANombre;
    }

    public JLabel getLblCodigoSistema() {
        return lblCodigoSistema;
    }

    public void setLblCodigoSistema(JLabel lblCodigoSistema) {
        this.lblCodigoSistema = lblCodigoSistema;
    }
    
    
    

}
