/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.gestionacademica.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.Estudiante;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.NivelAcademico;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.Periodo;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;

/**
 *
 * @author Carlos
 */
public abstract class MatriculaPanel extends ControladorCodefacInterface {

    /**
     * Creates new form MatriculaPanel
     */
    public MatriculaPanel() {
        initComponents();
        Periodo p;
        NivelAcademico na;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPasar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cmbNivel = new javax.swing.JComboBox<>();
        lblNivelAnterior = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPeriodoAnterior = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbNivelMatricula = new javax.swing.JComboBox<>();
        cmbPeriodoSiguiente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAlumnosSinMatricula = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAlumnosConMatricula = new javax.swing.JTable();
        btnAgregarEstudiante = new javax.swing.JButton();
        chkSeleccionarTodoTblSinMatricula = new javax.swing.JCheckBox();
        chkSeleccionarTodoTblConMatricula = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Matricula por grupo");

        btnPasar.setBackground(new java.awt.Color(255, 255, 255));
        btnPasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/flechaDer.png"))); // NOI18N
        btnPasar.setToolTipText("Matricular");

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/flechaIzq.png"))); // NOI18N
        btnRegresar.setToolTipText("Regresar");

        lblNivelAnterior.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNivelAnterior.setText("Cursos:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Buscar Por:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Periodo Matricula:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Cursos:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Lista de Alumnos disponibles");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Lista de Alumnos Matriculados");

        tblAlumnosSinMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Opcion", "Alumno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblAlumnosSinMatricula);
        if (tblAlumnosSinMatricula.getColumnModel().getColumnCount() > 0) {
            tblAlumnosSinMatricula.getColumnModel().getColumn(0).setMinWidth(60);
            tblAlumnosSinMatricula.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblAlumnosSinMatricula.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        tblAlumnosConMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Opcion", "Grabado", "Alumno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblAlumnosConMatricula);
        if (tblAlumnosConMatricula.getColumnModel().getColumnCount() > 0) {
            tblAlumnosConMatricula.getColumnModel().getColumn(0).setMinWidth(60);
            tblAlumnosConMatricula.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblAlumnosConMatricula.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btnAgregarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/add2.png"))); // NOI18N
        btnAgregarEstudiante.setText("Estudiante");

        chkSeleccionarTodoTblSinMatricula.setText("Seleccionar Todo");

        chkSeleccionarTodoTblConMatricula.setText("Seleccionar Todo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbNivelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbPeriodoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(chkSeleccionarTodoTblConMatricula)
                            .addGap(326, 326, 326)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPasar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAgregarEstudiante)
                                .addContainerGap())
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNivelAnterior)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbNivel, 0, 192, Short.MAX_VALUE)
                                    .addComponent(cmbPeriodoAnterior, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(chkSeleccionarTodoTblSinMatricula)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarEstudiante)
                            .addComponent(chkSeleccionarTodoTblConMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbPeriodoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNivelAnterior)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbPeriodoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cmbNivelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(btnPasar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRegresar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(chkSeleccionarTodoTblSinMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstudiante;
    private javax.swing.JButton btnPasar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox chkSeleccionarTodoTblConMatricula;
    private javax.swing.JCheckBox chkSeleccionarTodoTblSinMatricula;
    private javax.swing.JComboBox<NivelAcademico> cmbNivel;
    private javax.swing.JComboBox<NivelAcademico> cmbNivelMatricula;
    private javax.swing.JComboBox<Periodo> cmbPeriodoAnterior;
    private javax.swing.JComboBox<Periodo> cmbPeriodoSiguiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblNivelAnterior;
    private javax.swing.JTable tblAlumnosConMatricula;
    private javax.swing.JTable tblAlumnosSinMatricula;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnPasar() {
        return btnPasar;
    }

    public void setBtnPasar(JButton btnPasar) {
        this.btnPasar = btnPasar;
    }


    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }


    public JComboBox<Periodo> getCmbPeriodoAnterior() {
        return cmbPeriodoAnterior;
    }

    public void setCmbPeriodoAnterior(JComboBox<Periodo> cmbPeriodoAnterior) {
        this.cmbPeriodoAnterior = cmbPeriodoAnterior;
    }

    public JComboBox<Periodo> getCmbPeriodoSiguiente() {
        return cmbPeriodoSiguiente;
    }

    public void setCmbPeriodoSiguiente(JComboBox<Periodo> cmbPeriodoSiguiente) {
        this.cmbPeriodoSiguiente = cmbPeriodoSiguiente;
    }

    

    public JComboBox<NivelAcademico> getCmbNivel() {
        return cmbNivel;
    }

    public void setCmbNivel(JComboBox<NivelAcademico> cmbNivel) {
        this.cmbNivel = cmbNivel;
    }

    public JComboBox<NivelAcademico> getCmbNivelMatricula() {
        return cmbNivelMatricula;
    }

    public void setCmbNivelMatricula(JComboBox<NivelAcademico> cmbNivelMatricula) {
        this.cmbNivelMatricula = cmbNivelMatricula;
    }

    public JTable getTblAlumnosConMatricula() {
        return tblAlumnosConMatricula;
    }

    public void setTblAlumnosConMatricula(JTable tblAlumnosConMatricula) {
        this.tblAlumnosConMatricula = tblAlumnosConMatricula;
    }

    public JTable getTblAlumnosSinMatricula() {
        return tblAlumnosSinMatricula;
    }

    public void setTblAlumnosSinMatricula(JTable tblAlumnosSinMatricula) {
        this.tblAlumnosSinMatricula = tblAlumnosSinMatricula;
    }

    public JButton getBtnAgregarEstudiante() {
        return btnAgregarEstudiante;
    }

    public void setBtnAgregarEstudiante(JButton btnAgregarEstudiante) {
        this.btnAgregarEstudiante = btnAgregarEstudiante;
    }

    public JLabel getLblNivelAnterior() {
        return lblNivelAnterior;
    }

    public JCheckBox getChkSeleccionarTodoTblConMatricula() {
        return chkSeleccionarTodoTblConMatricula;
    }

    public void setChkSeleccionarTodoTblConMatricula(JCheckBox chkSeleccionarTodoTblConMatricula) {
        this.chkSeleccionarTodoTblConMatricula = chkSeleccionarTodoTblConMatricula;
    }

    public JCheckBox getChkSeleccionarTodoTblSinMatricula() {
        return chkSeleccionarTodoTblSinMatricula;
    }

    public void setChkSeleccionarTodoTblSinMatricula(JCheckBox chkSeleccionarTodoTblSinMatricula) {
        this.chkSeleccionarTodoTblSinMatricula = chkSeleccionarTodoTblSinMatricula;
    }

    
    
    
    
}
