/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.gestionacademica.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.componentes.ComponenteEnvioSmsPanel;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ComponenteSecundarioAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.CatalogoProducto;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.Periodo;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.RubroPlantillaMes;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.RubrosNivel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Carlos
 */
public abstract class NotificacionesDeudasPanel extends ControladorCodefacInterface {
    
    private ComponenteEnvioSmsPanel pnlSms=new ComponenteEnvioSmsPanel();

    /**
     * Creates new form NotificacionesDeudasPanel
     */
    public NotificacionesDeudasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnEnviar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        cmbPeriodo = new javax.swing.JComboBox<>();
        pnlCorreoConfigurar = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtCorreoTitulo = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblEspacio1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFormatoMensaje = new javax.swing.JTextArea();
        tabOpciones = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoRubroPorMes = new javax.swing.JComboBox<>();
        cmbMesFiltro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstFiltrosMes = new javax.swing.JList<>();
        btnAgregarMes = new javax.swing.JButton();
        btnEliminarMes = new javax.swing.JButton();
        lblEspacio2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoRubroGrupo = new javax.swing.JComboBox<>();
        lblEspacio5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbTipoRubroPorRubro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbRubro = new javax.swing.JComboBox<>();
        lblEspacio6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRubros = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnAgregarRubro = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnConsultarEstudiante = new javax.swing.JButton();
        chkSeleccionarTodos = new javax.swing.JCheckBox();

        btnEnviar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/32Pixeles/email.png"))); // NOI18N
        btnEnviar.setText("Enviar Correos");

        btnImprimir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/32Pixeles/reporte.png"))); // NOI18N
        btnImprimir.setText("Imprimir Notificaciones");

        cmbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPeriodoActionPerformed(evt);
            }
        });

        pnlCorreoConfigurar.setLayout(new java.awt.GridBagLayout());

        txtCorreoTitulo.setColumns(20);
        txtCorreoTitulo.setLineWrap(true);
        txtCorreoTitulo.setRows(5);
        jScrollPane6.setViewportView(txtCorreoTitulo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlCorreoConfigurar.add(jScrollPane6, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Titulo Correo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        pnlCorreoConfigurar.add(jLabel9, gridBagConstraints);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Notificar Deudas");

        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        jPanel4.add(lblEspacio1, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Formato del mensaje:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel4.add(jLabel6, gridBagConstraints);

        txtFormatoMensaje.setColumns(20);
        txtFormatoMensaje.setRows(5);
        txtFormatoMensaje.setText("Estimado [nombre_representante] la escuela le comunica\nque se le envia el reporte de deudas pendientes del\n[nombre_estudiante].\n\nGracias por su atención.\n");
        jScrollPane2.setViewportView(txtFormatoMensaje);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel4.add(jScrollPane2, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Tipo Rubro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbTipoRubroPorMes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbMesFiltro, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Filtro Por Mes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel7, gridBagConstraints);

        jScrollPane3.setViewportView(lstFiltrosMes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jScrollPane3, gridBagConstraints);

        btnAgregarMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/mas-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnAgregarMes, gridBagConstraints);

        btnEliminarMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cancel-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnEliminarMes, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblEspacio2, gridBagConstraints);

        tabOpciones.addTab("Por Mes", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Tipo Rubro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel2.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 18);
        jPanel2.add(cmbTipoRubroGrupo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(lblEspacio5, gridBagConstraints);

        tabOpciones.addTab("Por Grupo", jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Tipo Rubro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel3.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 18);
        jPanel3.add(cmbTipoRubroPorRubro, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Rubro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 8, 20);
        jPanel3.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 18);
        jPanel3.add(cmbRubro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel3.add(lblEspacio6, gridBagConstraints);

        tabOpciones.addTab("Por Rubro", jPanel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel4.add(tabOpciones, gridBagConstraints);

        jScrollPane1.setViewportView(tblRubros);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel4.add(jScrollPane1, gridBagConstraints);

        jScrollPane4.setViewportView(tblEstudiantes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 4.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel4.add(jScrollPane4, gridBagConstraints);

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);

        btnAgregarRubro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/add2.png"))); // NOI18N
        btnAgregarRubro.setText("Agregar");
        btnAgregarRubro.setFocusable(false);
        btnAgregarRubro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnAgregarRubro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAgregarRubro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAgregarRubro);

        btnQuitar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/facturaError.png"))); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.setFocusable(false);
        btnQuitar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnQuitar);

        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/cerrar-ico.png"))); // NOI18N
        btnLimpiar.setText("Limpiar Todo");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLimpiar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel4.add(jToolBar1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rubros");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 5);
        jPanel4.add(jLabel1, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Estudiantes");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 5);
        jPanel4.add(jLabel8, gridBagConstraints);

        btnConsultarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/32Pixeles/buscar2.png"))); // NOI18N
        btnConsultarEstudiante.setToolTipText("Consultar Estudiantes");
        btnConsultarEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 5, 0);
        jPanel4.add(btnConsultarEstudiante, gridBagConstraints);

        chkSeleccionarTodos.setText("Seleccionar Todos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel4.add(chkSeleccionarTodos, gridBagConstraints);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPeriodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMes;
    private javax.swing.JButton btnAgregarRubro;
    private javax.swing.JButton btnConsultarEstudiante;
    private javax.swing.JButton btnEliminarMes;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JCheckBox chkSeleccionarTodos;
    private javax.swing.JComboBox<RubroPlantillaMes> cmbMesFiltro;
    private javax.swing.JComboBox<Periodo> cmbPeriodo;
    private javax.swing.JComboBox<RubrosNivel> cmbRubro;
    private javax.swing.JComboBox<CatalogoProducto> cmbTipoRubroGrupo;
    private javax.swing.JComboBox<CatalogoProducto> cmbTipoRubroPorMes;
    private javax.swing.JComboBox<CatalogoProducto> cmbTipoRubroPorRubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JLabel lblEspacio2;
    private javax.swing.JLabel lblEspacio5;
    private javax.swing.JLabel lblEspacio6;
    private javax.swing.JList<RubroPlantillaMes> lstFiltrosMes;
    private javax.swing.JPanel pnlCorreoConfigurar;
    private javax.swing.JTabbedPane tabOpciones;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTable tblRubros;
    private javax.swing.JTextArea txtCorreoTitulo;
    private javax.swing.JTextArea txtFormatoMensaje;
    // End of variables declaration//GEN-END:variables

    @ComponenteSecundarioAnotacion(nombreCategoria = "Periodo Activo")
    public JComboBox<Periodo> getCmbPeriodo() {
        return cmbPeriodo;
    }

    public void setCmbPeriodo(JComboBox<Periodo> cmbPeriodo) {
        this.cmbPeriodo = cmbPeriodo;
    }

    
    @ComponenteSecundarioAnotacion(nombreCategoria = "Opciones",visible = false)
    public JButton getBtnEnviar() {
        return btnEnviar;
    }

    public void setBtnEnviar(JButton btnEnviar) {
        this.btnEnviar = btnEnviar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JComboBox<RubrosNivel> getCmbRubro() {
        return cmbRubro;
    }

    public void setCmbRubro(JComboBox<RubrosNivel> cmbRubro) {
        this.cmbRubro = cmbRubro;
    }


    public JComboBox<CatalogoProducto> getCmbTipoRubroGrupo() {
        return cmbTipoRubroGrupo;
    }

    public void setCmbTipoRubroGrupo(JComboBox<CatalogoProducto> cmbTipoRubroGrupo) {
        this.cmbTipoRubroGrupo = cmbTipoRubroGrupo;
    }

    public JComboBox<CatalogoProducto> getCmbTipoRubroPorMes() {
        return cmbTipoRubroPorMes;
    }

    public void setCmbTipoRubroPorMes(JComboBox<CatalogoProducto> cmbTipoRubroPorMes) {
        this.cmbTipoRubroPorMes = cmbTipoRubroPorMes;
    }

    public JComboBox<CatalogoProducto> getCmbTipoRubroPorRubro() {
        return cmbTipoRubroPorRubro;
    }

    public void setCmbTipoRubroPorRubro(JComboBox<CatalogoProducto> cmbTipoRubroPorRubro) {
        this.cmbTipoRubroPorRubro = cmbTipoRubroPorRubro;
    }

    

    public JTable getTblRubros() {
        return tblRubros;
    }

    public void setTblRubros(JTable tblRubros) {
        this.tblRubros = tblRubros;
    }

    public JTextArea getTxtFormatoMensaje() {
        return txtFormatoMensaje;
    }

    public void setTxtFormatoMensaje(JTextArea txtFormatoMensaje) {
        this.txtFormatoMensaje = txtFormatoMensaje;
    }

    public JButton getBtnQuitar() {
        return btnQuitar;
    }

    public void setBtnQuitar(JButton btnQuitar) {
        this.btnQuitar = btnQuitar;
    }

    public JButton getBtnAgregarMes() {
        return btnAgregarMes;
    }

    public void setBtnAgregarMes(JButton btnAgregarMes) {
        this.btnAgregarMes = btnAgregarMes;
    }

    public JButton getBtnEliminarMes() {
        return btnEliminarMes;
    }

    public void setBtnEliminarMes(JButton btnEliminarMes) {
        this.btnEliminarMes = btnEliminarMes;
    }

    public JComboBox<RubroPlantillaMes> getCmbMesFiltro() {
        return cmbMesFiltro;
    }

    public void setCmbMesFiltro(JComboBox<RubroPlantillaMes> cmbMesFiltro) {
        this.cmbMesFiltro = cmbMesFiltro;
    }

    public JList<RubroPlantillaMes> getLstFiltrosMes() {
        return lstFiltrosMes;
    }

    public void setLstFiltrosMes(JList<RubroPlantillaMes> lstFiltrosMes) {
        this.lstFiltrosMes = lstFiltrosMes;
    }

    @ComponenteSecundarioAnotacion(nombreCategoria = "Opciones")
    public JButton getBtnImprimir() {
        return btnImprimir;
    }

    public void setBtnImprimir(JButton btnImprimir) {
        this.btnImprimir = btnImprimir;
    }

    @ComponenteSecundarioAnotacion(nombreCategoria = "Servicio Mensajeria",visible = false)
    public ComponenteEnvioSmsPanel getPnlSms() {
        return pnlSms;
    }

    public JTabbedPane getTabOpciones() {
        return tabOpciones;
    }

    public JButton getBtnAgregarRubro() {
        return btnAgregarRubro;
    }

    public JButton getBtnConsultarEstudiante() {
        return btnConsultarEstudiante;
    }

    public JTable getTblEstudiantes() {
        return tblEstudiantes;
    }

    public JCheckBox getChkSeleccionarTodos() {
        return chkSeleccionarTodos;
    }

    @ComponenteSecundarioAnotacion(nombreCategoria = "Correo Configurar",visible = false)    
    public JPanel getPnlCorreoConfigurar() {
        return pnlCorreoConfigurar;
    }

    public JTextArea getTxtCorreoTitulo() {
        return txtCorreoTitulo;
    }
    
    

    
    
    
}
