/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.gestionacademica.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.CatalogoProducto;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.Periodo;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.RubrosNivel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author Carlos
 */
public abstract class NotificacionesDeudasPanel extends ControladorCodefacInterface {

    /**
     * Creates new form NotificacionesDeudasPanel
     */
    public NotificacionesDeudasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRubros = new javax.swing.JTable();
        btnEnviar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        chkEnero = new javax.swing.JRadioButton();
        chkFebrero = new javax.swing.JRadioButton();
        chkMarzo = new javax.swing.JRadioButton();
        chkAbril = new javax.swing.JRadioButton();
        chkMayo = new javax.swing.JRadioButton();
        chkJunio = new javax.swing.JRadioButton();
        chkJulio = new javax.swing.JRadioButton();
        chkAgosto = new javax.swing.JRadioButton();
        chkSeptiembre = new javax.swing.JRadioButton();
        chkOctubre = new javax.swing.JRadioButton();
        chkNoviembre = new javax.swing.JRadioButton();
        chkDiciembre = new javax.swing.JRadioButton();
        btnAgregarPorMes = new javax.swing.JButton();
        cmbTipoRubroPorMes = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoRubroGrupo = new javax.swing.JComboBox<>();
        btnAgregarPorGrupo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbTipoRubroPorRubro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbRubro = new javax.swing.JComboBox<>();
        btnAgregarPorRubro = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFormatoMensaje = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnQuitar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Notificar Deudas");

        jLabel1.setText("Periodo Activo:");

        tblRubros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRubros);

        btnEnviar.setText("ENVIAR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Tipo Rubro:");

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Meses Generar"));

        chkEnero.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkEnero.setText("Enero");
        chkEnero.setFocusable(false);
        chkEnero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkEnero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkEnero);

        chkFebrero.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkFebrero.setText("Febrero");
        chkFebrero.setFocusable(false);
        chkFebrero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkFebrero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkFebrero);

        chkMarzo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkMarzo.setText("Marzo");
        chkMarzo.setFocusable(false);
        chkMarzo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkMarzo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkMarzo);

        chkAbril.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkAbril.setText("Abril");
        chkAbril.setFocusable(false);
        chkAbril.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkAbril.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkAbril);

        chkMayo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkMayo.setText("Mayo");
        chkMayo.setFocusable(false);
        chkMayo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkMayo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkMayo);

        chkJunio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkJunio.setText("Junio");
        chkJunio.setFocusable(false);
        chkJunio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkJunio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkJunio);

        chkJulio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkJulio.setText("Julio");
        chkJulio.setFocusable(false);
        chkJulio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkJulio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkJulio);

        chkAgosto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkAgosto.setText("Agosto");
        chkAgosto.setFocusable(false);
        chkAgosto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkAgosto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkAgosto);

        chkSeptiembre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkSeptiembre.setText("Septiembre");
        chkSeptiembre.setFocusable(false);
        chkSeptiembre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkSeptiembre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkSeptiembre);

        chkOctubre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkOctubre.setText("Octubre");
        chkOctubre.setFocusable(false);
        chkOctubre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkOctubre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkOctubre);

        chkNoviembre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkNoviembre.setText("Noviembre");
        chkNoviembre.setFocusable(false);
        chkNoviembre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkNoviembre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkNoviembre);

        chkDiciembre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chkDiciembre.setText("Diciembre");
        chkDiciembre.setFocusable(false);
        chkDiciembre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chkDiciembre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(chkDiciembre);

        btnAgregarPorMes.setText("Agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(cmbTipoRubroPorMes, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarPorMes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPorMes)
                    .addComponent(cmbTipoRubroPorMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Por Mes", jPanel1);

        jLabel2.setText("Tipo Rubro:");

        btnAgregarPorGrupo.setText("Agregar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cmbTipoRubroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAgregarPorGrupo)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipoRubroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPorGrupo))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Por Grupo", jPanel2);

        jLabel3.setText("Tipo Rubro:");

        jLabel5.setText("Rubro:");

        btnAgregarPorRubro.setText("Agregar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoRubroPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarPorRubro)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoRubroPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPorRubro))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Por Rubro", jPanel3);

        btnLimpiar.setText("LIMPIAR");

        txtFormatoMensaje.setColumns(20);
        txtFormatoMensaje.setRows(5);
        txtFormatoMensaje.setText("Estimado [nombre_representante] la escuela le comunica\nque se le envia el reporte de deudas pendientes del\n[nombre_estudiante].\n\nGracias por su atención.\n");
        jScrollPane2.setViewportView(txtFormatoMensaje);

        jLabel6.setText("Formato del mensaje:");

        jLabel7.setText("Listado de Rubros que se van a generar para enviar los comunicados.");

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/salir-ico.png"))); // NOI18N
        btnQuitar.setText("Quitar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuitar))
                            .addComponent(jScrollPane1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnQuitar))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPorGrupo;
    private javax.swing.JButton btnAgregarPorMes;
    private javax.swing.JButton btnAgregarPorRubro;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JRadioButton chkAbril;
    private javax.swing.JRadioButton chkAgosto;
    private javax.swing.JRadioButton chkDiciembre;
    private javax.swing.JRadioButton chkEnero;
    private javax.swing.JRadioButton chkFebrero;
    private javax.swing.JRadioButton chkJulio;
    private javax.swing.JRadioButton chkJunio;
    private javax.swing.JRadioButton chkMarzo;
    private javax.swing.JRadioButton chkMayo;
    private javax.swing.JRadioButton chkNoviembre;
    private javax.swing.JRadioButton chkOctubre;
    private javax.swing.JRadioButton chkSeptiembre;
    private javax.swing.JComboBox<Periodo> cmbPeriodo;
    private javax.swing.JComboBox<RubrosNivel> cmbRubro;
    private javax.swing.JComboBox<CatalogoProducto> cmbTipoRubroGrupo;
    private javax.swing.JComboBox<CatalogoProducto> cmbTipoRubroPorMes;
    private javax.swing.JComboBox<CatalogoProducto> cmbTipoRubroPorRubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblRubros;
    private javax.swing.JTextArea txtFormatoMensaje;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarPorGrupo() {
        return btnAgregarPorGrupo;
    }

    public void setBtnAgregarPorGrupo(JButton btnAgregarPorGrupo) {
        this.btnAgregarPorGrupo = btnAgregarPorGrupo;
    }

    public JButton getBtnAgregarPorMes() {
        return btnAgregarPorMes;
    }

    public void setBtnAgregarPorMes(JButton btnAgregarPorMes) {
        this.btnAgregarPorMes = btnAgregarPorMes;
    }

    public JButton getBtnAgregarPorRubro() {
        return btnAgregarPorRubro;
    }

    public void setBtnAgregarPorRubro(JButton btnAgregarPorRubro) {
        this.btnAgregarPorRubro = btnAgregarPorRubro;
    }

    public JButton getBtnEnviar() {
        return btnEnviar;
    }

    public void setBtnEnviar(JButton btnEnviar) {
        this.btnEnviar = btnEnviar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JRadioButton getChkAbril() {
        return chkAbril;
    }

    public void setChkAbril(JRadioButton chkAbril) {
        this.chkAbril = chkAbril;
    }

    public JRadioButton getChkAgosto() {
        return chkAgosto;
    }

    public void setChkAgosto(JRadioButton chkAgosto) {
        this.chkAgosto = chkAgosto;
    }

    public JRadioButton getChkDiciembre() {
        return chkDiciembre;
    }

    public void setChkDiciembre(JRadioButton chkDiciembre) {
        this.chkDiciembre = chkDiciembre;
    }

    public JRadioButton getChkEnero() {
        return chkEnero;
    }

    public void setChkEnero(JRadioButton chkEnero) {
        this.chkEnero = chkEnero;
    }

    public JRadioButton getChkFebrero() {
        return chkFebrero;
    }

    public void setChkFebrero(JRadioButton chkFebrero) {
        this.chkFebrero = chkFebrero;
    }

    public JRadioButton getChkJulio() {
        return chkJulio;
    }

    public void setChkJulio(JRadioButton chkJulio) {
        this.chkJulio = chkJulio;
    }

    public JRadioButton getChkJunio() {
        return chkJunio;
    }

    public void setChkJunio(JRadioButton chkJunio) {
        this.chkJunio = chkJunio;
    }

    public JRadioButton getChkMarzo() {
        return chkMarzo;
    }

    public void setChkMarzo(JRadioButton chkMarzo) {
        this.chkMarzo = chkMarzo;
    }

    public JRadioButton getChkMayo() {
        return chkMayo;
    }

    public void setChkMayo(JRadioButton chkMayo) {
        this.chkMayo = chkMayo;
    }

    public JRadioButton getChkNoviembre() {
        return chkNoviembre;
    }

    public void setChkNoviembre(JRadioButton chkNoviembre) {
        this.chkNoviembre = chkNoviembre;
    }

    public JRadioButton getChkOctubre() {
        return chkOctubre;
    }

    public void setChkOctubre(JRadioButton chkOctubre) {
        this.chkOctubre = chkOctubre;
    }

    public JRadioButton getChkSeptiembre() {
        return chkSeptiembre;
    }

    public void setChkSeptiembre(JRadioButton chkSeptiembre) {
        this.chkSeptiembre = chkSeptiembre;
    }

    public JComboBox<Periodo> getCmbPeriodo() {
        return cmbPeriodo;
    }

    public void setCmbPeriodo(JComboBox<Periodo> cmbPeriodo) {
        this.cmbPeriodo = cmbPeriodo;
    }

    public JComboBox<RubrosNivel> getCmbRubro() {
        return cmbRubro;
    }

    public void setCmbRubro(JComboBox<RubrosNivel> cmbRubro) {
        this.cmbRubro = cmbRubro;
    }


    public JComboBox<CatalogoProducto> getCmbTipoRubroGrupo() {
        return cmbTipoRubroGrupo;
    }

    public void setCmbTipoRubroGrupo(JComboBox<CatalogoProducto> cmbTipoRubroGrupo) {
        this.cmbTipoRubroGrupo = cmbTipoRubroGrupo;
    }

    public JComboBox<CatalogoProducto> getCmbTipoRubroPorMes() {
        return cmbTipoRubroPorMes;
    }

    public void setCmbTipoRubroPorMes(JComboBox<CatalogoProducto> cmbTipoRubroPorMes) {
        this.cmbTipoRubroPorMes = cmbTipoRubroPorMes;
    }

    public JComboBox<CatalogoProducto> getCmbTipoRubroPorRubro() {
        return cmbTipoRubroPorRubro;
    }

    public void setCmbTipoRubroPorRubro(JComboBox<CatalogoProducto> cmbTipoRubroPorRubro) {
        this.cmbTipoRubroPorRubro = cmbTipoRubroPorRubro;
    }

    

    public JTable getTblRubros() {
        return tblRubros;
    }

    public void setTblRubros(JTable tblRubros) {
        this.tblRubros = tblRubros;
    }

    public JTextArea getTxtFormatoMensaje() {
        return txtFormatoMensaje;
    }

    public void setTxtFormatoMensaje(JTextArea txtFormatoMensaje) {
        this.txtFormatoMensaje = txtFormatoMensaje;
    }

    public JButton getBtnQuitar() {
        return btnQuitar;
    }

    public void setBtnQuitar(JButton btnQuitar) {
        this.btnQuitar = btnQuitar;
    }
    
    
    
    
}
