/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.9.5)*/
create table DESCUENTO( 
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1), 
    NOMBRE varchar(128), 
    DESCRIPCION varchar(1024), 
    FECHA_INICIO timestamp, 
    FECHA_FIN timestamp, 
    ALCANCE varchar(1), 
    EMPRESA_ID BIGINT,  

    FECHA_CREACION timestamp, 
    FECHA_ULTIMA_EDICION timestamp, 
    USUARIO_CREACION_ID BIGINT,  
    USUARIO_ULTIMA_EDICION_ID BIGINT,  
    ESTADO varchar(1),
 
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.9.7)*/
create table DESCUENTO_PRODUCTO_DETALLE( 
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1), 
    DESCUENTO_ID BIGINT, 
    PRODUCTO_ID BIGINT,  
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.9.7)*/
create table DESCUENTO_CONDICION_PRECIO( 
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1), 
    DESCUENTO_ID BIGINT, 
    NUMERO_PRECIO INT,
    PORCENTAJE_DESCUENTO decimal(13,5),
 
    primary key (ID)
);


