/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  PC
 * Created: 14-nov-2017
 */
create table PRODUCTO
(
    ID_PRODUCTO BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1),
    CATALOGO_PRODUCTO_ID BIGINT,
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.7.9.7)*/
    EMPRESA_ID BIGINT, 
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.8.9.3)*/
    MARCA_PRODUCTO_ID BIGINT, 
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.2.3)*/
    CASA_COMERCIAL_ID BIGINT, 
    CODIGO_PERSONALIZADO varchar(70),
    CODIGO_EAN varchar(70),
    CODIGO_UPC varchar(70),
    TIPO_PRODUCTO_COD varchar(1),
    NOMBRE varchar(300),
    VALOR_UNITARIO decimal(13,5),
    ESTADO varchar(1),
    UBICACION varchar(100),
    GARANTIA varchar(1),
    CANTIDAD_MINIMA integer,
    PRECIO_DISTRIBUIDOR decimal(13,5),
    PRECIO_TARJETA decimal(13,5),
    STOCK_INICIAL bigint,
    MARCA varchar(50),
    IMAGEN varchar(100),
    CARACTERISTICAS varchar(1024),
    OBSERVACIONES varchar(1024),  
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.3)*/
    MANEJAR_INVENTARIO  varchar(1),  
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.7.8.1)*/
    GENERAR_CODIGO_BARRAS  varchar(1), 
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.7.8.2)*/
    TRANSPORTAR_EN_GUIA_REMISION  varchar(1),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.8.0.9)*/
    OCULTAR_DETALLE_VENTA varchar(1),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.8.2.5)*/
    PRECIO_SIN_SUBSIDIO decimal(13,5),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.8.5.3)*/
    PVP_4 decimal(13,5),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.8.5.3)*/
    PVP_5 decimal(13,5),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.8.5.3)*/
    PVP_6 decimal(13,5),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.2.3)*/
    NOMBRE_GENERICO varchar(1024),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.1.2)*/
    APLICACION_PRODUCTO varchar(1024),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.1.2)*/
    TIPO_ID BIGINT, 
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.1.2)*/
    SEGMENTO_ID BIGINT, 
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.3.6)*/
    ACTUALIZAR_PRECIO varchar(1),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.4.1)*/
    DISPONIBLE_VENTA varchar(1),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.4.1)*/
    DISPONIBLE_COMPRA varchar(1),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.4.2)*/
    FECHA_ULTIMA_ACTUALIZACION_PRECIO TIMESTAMP,
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.4.4)*/
    REGISTRO_SANITARIO varchar(128),
  /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.7.1,MOSTRAR_ERROR=NO)*/
    FECHA_CREACION timestamp, 
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.7.1,MOSTRAR_ERROR=NO)*/
    FECHA_ULTIMA_EDICION timestamp, 
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.7.1,MOSTRAR_ERROR=NO)*/
    USUARIO_CREACION_ID BIGINT,  
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.7.1,MOSTRAR_ERROR=NO)*/
    USUARIO_ULTIMA_EDICION_ID BIGINT,     
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.3.0.4.4)*/
    COD_PRESENTACION_DEFECTO_VENTA varchar(14),
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.3.0.4.4)*/
    COD_PRESENTACION_DEFECTO_COMPRA varchar(14),
    primary key (ID_PRODUCTO)
);


create table PRODUCTO_ENSAMBLE
( 
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1) , 
    COMPONENTE_ENSAMBLE BIGINT,
    PRODUCTO_ENSAMBLE BIGINT, 
    CANTIDAD decimal(13,5),
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.8.9.3)*/
create table MARCA_PRODUCTO
(
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1) , 
    EMPRESA_ID BIGINT, 
    NOMBRE varchar(100),
    DESCRIPCION varchar(100),
    ESTADO varchar(1),
    FECHA_CREACION TIMESTAMP,
    FECHA_ULTIMA_MODIFICACION TIMESTAMP,
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.2.2)*/
create table CASA_COMERCIAL
(
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1) , 
    EMPRESA_ID BIGINT, 
    NOMBRE varchar(100),
    DESCRIPCION varchar(100),
    ESTADO varchar(1),
    FECHA_CREACION TIMESTAMP,
    FECHA_ULTIMA_MODIFICACION TIMESTAMP,
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.2.5)*/
create table PRODUCTO_PRESENTACION_DETALLE
(
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1) , 
    CANTIDAD decimal(13,5),
    PRESENTACION_PRODUCTO_ID BIGINT not null,
    PRODUCTO_ORIGINAL_ID BIGINT,
    PRODUCTO_EMPAQUETADO_ID BIGINT,
    /*@AGREGAR_COLUMNA(VERSION_SISTEMA=1.2.9.3.1)*/
    TIPO varchar(1), 
    primary key (ID)
);



/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.1.2)*/
create table SEGMENTO_PRODUCTO( 
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1), 
    NOMBRE varchar(100),
    DESCRIPCION varchar(100),
    EMPRESA_ID BIGINT,  

    FECHA_CREACION timestamp, 
    FECHA_ULTIMA_EDICION timestamp, 
    USUARIO_CREACION_ID BIGINT,  
    USUARIO_ULTIMA_EDICION_ID BIGINT,  
    ESTADO varchar(1),
 
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.1.2)*/
create table TIPO_PRODUCTO( 
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1), 
    NOMBRE varchar(100),
    DESCRIPCION varchar(100),
    EMPRESA_ID BIGINT,  

    FECHA_CREACION timestamp, 
    FECHA_ULTIMA_EDICION timestamp, 
    USUARIO_CREACION_ID BIGINT,  
    USUARIO_ULTIMA_EDICION_ID BIGINT,  
    ESTADO varchar(1),
 
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.2.4)*/
create table PRESENTACION_PRODUCTO
(
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY (START WITH 1) , 
    EMPRESA_ID BIGINT, 
    NOMBRE varchar(100),
    DESCRIPCION varchar(100),
    ESTADO varchar(1),
    FECHA_CREACION TIMESTAMP,
    FECHA_ULTIMA_MODIFICACION TIMESTAMP,
    primary key (ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.4.6)*/
create table GARANTIA
(
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY( START WITH 1),
    NUMERO INT,
    NOMBRE varchar(120),
    CAPACIDAD INT,    
    FECHA_INGRESO timestamp,
    FECHA_SALIDA timestamp,
    DESCRIPCION_INGRESO varchar(1024),
    DESCRIPCION_SALIDA varchar(1024),
    BODEGA_ID BIGINT,  

    RESPONSABLE_ID BIGINT,  
    FECHA_CREACION timestamp, 
    FECHA_ULTIMA_EDICION timestamp, 
    USUARIO_CREACION_ID BIGINT,  
    USUARIO_ULTIMA_EDICION_ID BIGINT,  
    ESTADO varchar(1),
    primary key(ID)
);

/*@AGREGAR_TABLA(VERSION_SISTEMA=1.2.9.5.3)*/
create table PRODUCTO_ACTIVIDAD
(
    ID BIGINT not null GENERATED ALWAYS AS IDENTITY( START WITH 1),
    ORDEN INT,
    NOMBRE varchar(120),
    DESCRIPCION varchar(520),

    FECHA_CREACION timestamp, 
    FECHA_ULTIMA_EDICION timestamp, 
    USUARIO_CREACION_ID BIGINT,  
    USUARIO_ULTIMA_EDICION_ID BIGINT,  
    ESTADO varchar(1),
    
    PRODUCTO_ID BIGINT,  
    primary key(ID),
    CONSTRAINT ACTIVIDAD_PRODUCTO_FK FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID_PRODUCTO)
);