/**
 * Author:  PC
 * Created: 14-nov-2017
 */

INSERT INTO IMPUESTO (IVA) VALUES('1');
INSERT INTO IMPUESTO (IVA) VALUES('2');
INSERT INTO IMPUESTO (IVA) VALUES('3');
INSERT INTO IMPUESTO (IVA) VALUES('4');
INSERT INTO IMPUESTO (ICE) VALUES ('3011');
INSERT INTO IMPUESTO (ICE) VALUES ('3021');
INSERT INTO IMPUESTO (ICE) VALUES ('3023');
INSERT INTO IMPUESTO (ICE) VALUES ('3031');
INSERT INTO IMPUESTO (ICE) VALUES ('3041');
INSERT INTO IMPUESTO (ICE) VALUES ('3051'); 
INSERT INTO IMPUESTO (ICE) VALUES ('3072');
INSERT INTO IMPUESTO (ICE) VALUES ('3073');
INSERT INTO IMPUESTO (ICE) VALUES ('3074');
INSERT INTO IMPUESTO (ICE) VALUES ('3075');
INSERT INTO IMPUESTO (ICE) VALUES ('3077');
INSERT INTO IMPUESTO (ICE) VALUES ('3078');
INSERT INTO IMPUESTO (ICE) VALUES ('3079');
INSERT INTO IMPUESTO (ICE) VALUES ('3080');
INSERT INTO IMPUESTO (ICE) VALUES ('3081');
INSERT INTO IMPUESTO (ICE) VALUES ('3092');
INSERT INTO IMPUESTO (ICE) VALUES ('3171');
INSERT INTO IMPUESTO (ICE) VALUES ('3172');
INSERT INTO IMPUESTO (ICE) VALUES ('3173');
INSERT INTO IMPUESTO (ICE) VALUES ('3174');
INSERT INTO IMPUESTO (ICE) VALUES ('3175');
INSERT INTO IMPUESTO (ICE) VALUES ('3176');
INSERT INTO IMPUESTO (ICE) VALUES ('3610');
INSERT INTO IMPUESTO (ICE) VALUES ('3620');
INSERT INTO IMPUESTO (ICE) VALUES ('3630');
INSERT INTO IMPUESTO (ICE) VALUES ('3640');
INSERT INTO IMPUESTO (ICE) VALUES ('3650');
INSERT INTO IMPUESTO (ICE) VALUES ('3660');
INSERT INTO IMPUESTO (IRBPNR) VALUES ('1');