INSERT INTO NIVEL(NOMBRE,DESCRIPCION,ORDEN,ESTADO) 
VALUES ('Segundo grado','primer grado',5,'A'),
('Primer grado','primer grado',4,'A'),
('Basica','basica',3,'A'),
('Inicia1 2','Inicial 2',2,'A'),
('Inicia1 1','Inicial 1',1,'A')
;

INSERT INTO PERIODO (NOMBRE, FECHA_INICIO, FECHA_FIN, ESTADO) 
VALUES 
('2017 enero - 2018 junio', '2017-01-01', '2017-06-30', 'A'),
('2017 julio - 2018 diciembre', '2017-07-01', '2017-12-24', 'I'),
('2018 enero - 2018 junio', '2018-01-01', '2018-06-30', 'I'),
('2018 julio - 2018 diciembre', '2018-07-01', '2018-12-24', 'I')
;

INSERT INTO AULA (NOMBRE, UBICACION, ESTADO) 
VALUES ('Ninguno', 'Ninguno', 'A'),
('Aula 1', 'Primer piso', 'A'),
('Aula 2', 'Segundo piso', 'A')
;

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, TIPO_OPERADOR, RAZON_SOCIAL, NOMBRE_LEGAL, TIPO_IDENTIFICACION, IDENTIFICACION, TIPO_CLIENTE, DIRECCION, TELEFONO_CONVENCIONAL, EXTENSION_TELEFONO, TELEFONO_CELULAR, CORREO_ELECTRONICO, ACTIVIDAD_COMERCIAL, ESTADO,SRI_FORMA_PAGO_ID,NACIONALIDAD_ID) 
VALUES 
('María José', 'Pillajo', 'C', 'María José Pillajo', NULL, '05', '1718559592', 'CLIENTE', 'ARMENIA 2, LA RIVERA CONJUNTO CHIMBORAZO CASA NO. 6 ', '22093992', '0', '', 'mygoldenworld@gmail.com', NULL, 'A',1,53),
('Carmen', 'Augusta', 'C', 'Carmen Augusta', NULL, '05', '1715922140', 'CLIENTE', 'SAN PEDRO DE TADOABA', '', '0', '0987446497', 'mygoldenworld@gmail.com', NULL, 'A',1,53),
('Franklin', 'Lopez Acuña', 'C', 'Franklin Lopez Acuña', NULL, '05', '1715184493', 'CLIENTE', 'CONOCOTO', '', '0', '0998341606', 'mygoldenworld@gmail.com', NULL, 'A',1,53),
('Pedro ', 'Risueño', 'C', 'Pedro Risueño', NULL, '05', '1719852124', 'CLIENTE', 'CONOCOTO', '23696011', '0', '', 'mygoldenworld@gmail.com', NULL, 'A',1,53),
('AGENCIA DE REGULACION  Y CONTROL HIDROCARBURIFERO', 'AGENCIA DE REGULACION  Y CONTROL HIDROCARBURIFERO', 'C', 'AGENCIA DE REGULACION  Y CONTROL HIDROCARBURIFERO', NULL, '04', '1768158680001', 'CLIENTE', 'CONOCOTO', '23996500', '0', '', 'mygoldenworld@gmail.com', NULL, 'A',1,53),
('Carlos', 'Perez', 'C', 'Carlos Perez', NULL, '04', '1719468108001', 'CLIENTE', 'Sangolqui', '022087044', '0', '0983528439', 'jcp_computer@hotmail.com', NULL, 'A',1,53),
('Juan', 'Loya', 'C', 'JUAN Loya', NULL, '04', '1724218951001', 'CLIENTE', 'Conocoto', '022087065', '0', '0983528439', 'juancarlos100pl@hotmail.com', NULL, 'A',1,53)
;

INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (NULL, 53, 'P001', 'PX001', '1758007734', '', 'THOMAS ANDRES', 'PROAÑO PILLAJO', 'M', '2017-03-25', '', '', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (NULL, 53, 'P002', 'PX002', '', '', 'LUCIANA', 'DIAZ ALDANA', 'F', '2016-03-08', '', '', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (NULL, 53, 'P003', 'PX003', '1756947535', '', 'SABRINA ANAHI', 'LOPEZ ORTIZ', 'F', '2015-07-30', '', '', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (NULL, 53, 'P004', 'PX004', '', '', 'SOFIA DANIELA', 'RISUEÑO INFANTE', 'F', '2014-05-26', '', '', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (NULL, 53, 'P005', 'PX005', '1728303080', '', 'ELIAN ALEJANDRO', 'MAYORGA BAYAS', 'M', '2013-08-22', '', '', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (6, 53, 'C001', 'X001', '1717171717', 'jperez@gmail.com', 'JUAN', 'PEREZ', 'M', '1991-05-02', '022087044', '0983528439', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (6, 53, 'C002', 'X002', '1616161616', 'dperez@gmail.com', 'DIEGO', 'PEREZ', 'F', '1991-06-22', '022087044', '0983528439', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (7, 53, 'C004', 'X004', '1313131313', 'asuarez@gmail.com', 'ALFONSO', 'SUAREZ', 'M', '1991-11-02', '022087044', '0983528439', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (7, 53, 'C005', 'X005', '1212121212', 'csuarez@gmail.com', 'CARMEN', 'SUAREZ', 'F', '1991-08-02', '022087044', '0983528439', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (7, 53, 'C006', 'X007', '1414141414', 'clopez@gmail.com', 'CARLOS', 'LOPEZ', 'M', '1990-03-02', '022087014', '0983528439', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');
INSERT INTO ESTUDIANTE (REPRESENTANTE1_ID, NACIONALIDAD_ID, CODSISTEMA, CODAUXILIAR, CEDULA, EMAIL, NOMBRES, APELLIDOS, GENERO, FECHA_NACIMIENTO, TELEFONO, CELULAR, DIRECCION, ADICIONALES, ETNIA, DISCAPACIDAD, CONADIS, TIPO_DISCAPACIDAD, OBS_DISCAPACIDAD, PORCENTAJE_DISCAPACIDAD, ESTADO) 
	VALUES (7, 53, 'C007', 'X007', '1313131313', 'lgarcia@gmail.com', 'LUIS', 'GARCIA', 'M', '1991-01-02', '022123014', '0983528439', NULL, NULL, NULL, 'n', '', 'n', NULL, NULL, 'A');



INSERT INTO CATEGORIA_PRODUCTO (NOMBRE, DESCRIPCION, IMAGEN_PATH, ESTADO) 
	VALUES ('Rubros institucionales', 'Rubros institucionales', NULL, 'A');
INSERT INTO CATEGORIA_PRODUCTO (NOMBRE, DESCRIPCION, IMAGEN_PATH, ESTADO) 
	VALUES ('Rubros externos', 'Rubros externos', NULL, 'A');


INSERT INTO CATALOGO_PRODUCTO (CATEGORIA_ID, NOMBRE, DESCRIPCION, IVA_ID, ICE_ID, IRBPNR_ID, ESTADO, MODULO_COD, TIPO_COD) 
	VALUES (1,'Matriculas', NULL, 1, NULL, NULL, 'A', 'ACAS', 'MA');
INSERT INTO CATALOGO_PRODUCTO (CATEGORIA_ID, NOMBRE, DESCRIPCION, IVA_ID, ICE_ID, IRBPNR_ID, ESTADO, MODULO_COD, TIPO_COD) 
	VALUES (1,'Pensiones', NULL, 1, NULL, NULL, 'A', 'ACAS', 'NA');
INSERT INTO CATALOGO_PRODUCTO (CATEGORIA_ID, NOMBRE, DESCRIPCION, IVA_ID, ICE_ID, IRBPNR_ID, ESTADO, MODULO_COD, TIPO_COD) 
	VALUES (2,'Servicios complementarios', NULL, 1, NULL, NULL, 'A', 'ACAS', 'NA');
