UPDATE PRODUCTO SET VALOR_UNITARIO = VALOR_UNITARIO *(112/CAST(115 AS DOUBLE)), PRECIO_DISTRIBUIDOR =PRECIO_DISTRIBUIDOR *(112/CAST(115 AS DOUBLE)),PRECIO_TARJETA =PRECIO_TARJETA*(112/CAST(115 AS DOUBLE)), PVP_4 =PVP_4 *(112/CAST(115 AS DOUBLE)),PVP_5 =PVP_5 *(112/CAST(115 AS DOUBLE)),PVP_6 =PVP_6 *(112/CAST(115 AS DOUBLE)) WHERE ID_PRODUCTO IN
(
	SELECT P.ID_PRODUCTO FROM ROOT.PRODUCTO P INNER JOIN CATALOGO_PRODUCTO CP ON P.CATALOGO_PRODUCTO_ID =CP.ID WHERE CP.IVA_ID =11
) 
;