/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.servidorinterfaz.enumerados;

/**
 *
 * @author CARLOS_CODESOFT
 */
public enum ParteVehiculoEnum {
    CAPOT("CAPOT"),
    TECHO("TECHO"),
    COMPUERTA("COMPUERTA"),
    PUERTA_DELANT_LH("PUERTA DELANT LH"),
    PUERTA_DELANT_RH("PUERTA DELANT RH"),
    PUERTA_POST_RH("PUERTA POST RH"),
    PUERTA_POST_LH("PUERTA POST LH"),
    GUARDAFANGO_DELANT_LH("GUARDAFANGO DELANT LH"),
    GUARDAFANGO_DELANT_RH("GUARDAFANGO DELANT RH"),
    MOLDURA_CENTRAL_LH("MOLDURA CENTRAL LH"),
    MOLDURA_POST_LH("MOLDURA POST LH"),
    MOLDURA_DELANT_LH("MOLDURA DELANT LH"),
    MOLDURA_CENTRAL_RH("MOLDURA CENTRAL RH"),
    MOLDURA_POST_RH("MOLDURA POST RH"),
    MOLDURA_DELANT_RH("MOLDURA DELANT RH"),
    PARANTE_CENTRAL_LH("PARANTE CENTRAL LH"),
    PARANTE_DELANT_LH("PARANTE DELANT LH"),
    PARANTE_POST_LH("PARANTE POST LH"),
    PARANTE_CENTRAL_RH("PARANTE CENTRAL RH"),
    PARANTE_DELANT_RH("PARANTE DELANT RH"),
    PARANTE_POST_RH("PARANTE POST RH"),
    ZOCALO_DELANT_LH("ZÓCALO DELANT LH"),
    ZOCALO_DELANT_RH("ZÓCALO DELANT RH"),
    ZOCALO_POST_LH("ZÓCALO POST LH"),
    ZOCALO_POST_RH("ZÓCALO POST RH"),
    BAJO_PISO("BAJO PISO"),
    PARANTE_INTERNO_LH("PARANTE INTERNO LH"),
    PARANTE_INTERNO_RH("PARANTE INTERNO RH"),
    LATERAL_LH("LATERAL LH"),
    LATERAL_RH("LATERAL RH"),
    PARACHOQUE_DELANT("PARACHOQUE DELANT"),
    PARACHOQUE_POST("PARACHOQUE POST"),
    MASCARILLA("MASCARILLA"),
    NIQUELADO("NIQUELADO"),
    FARO_DELANT_LH("FARO DELANT LH"),
    FARO_DELANT_RH("FARO DELANT RH"),
    FARO_POST_LH("FARO POST LH"),
    FARO_POST_RH("FARO POST RH"),
    LUZ_DE_STOP("LUZ DE STOP"),
    LUZ_DE_SALON("LUZ DE SALON"),
    TAPIZADO_DELANT_LH("TAPIZADO DELANT LH"),
    TAPIZADO_DELANT_RH("TAPIZADO DELANT RH"),
    TAPIZADO_POST_LH("TAPIZADO POST LH"),
    TAPIZADO_POST_RH("TAPIZADO POST RH"),
    PARABRISAS_DELANT("PARABRISAS DELANT"),
    PARABRISAS_POST("PARABRISAS POST"),
    VENTANA_DELANT_LH("VENTANA DELANT LH"),
    VENTANA_DELANT_RH("VENTANA DELANT RH"),
    VENTANA_POST_LH("VENTANA POST LH"),
    VENTANA_POST_RH("VENTANA POST RH"),
    CONSOLA_CENTRAL("CONSOLA CENTRAL"),
    TABLERO("TABLERO"),
    ODOMETRO("ODOMETRO"),
    ASIENTOS("ASIENTOS"),
    TECHO_INTERNO("TECHO_INTERNO"),
    CONTROL_DE_ENCENDIDO("CONTROL DE ENCENDIDO"),
    PINTURA("PINTURA"),
    TAPA_COMBUSTIBLE("TAPA COMBUSTIBLE"),
    MANIJAS("MANIJAS"),
    PIANOS_PLUMAS("PIANOS/PLUMAS"),
    PERNOS_OXIDADOS("PERNOS ÓXIDADOS"),
    RETROVISORES("RETROVISORES"),
    MOLDURA("MOLDURA INTERNA/EXTERNA"),
    AROS("AROS"),
    ANTENA("ANTENA"),
    LLUVIA_ACIDA("LLUVIA ÁCIDA"),
    
    TESTIGOS_ENCENDIDOS("TESTIGOS ENCENDIDOS"),
    PROBLEMA_CABLEADO_ARNEsES("PROBLEMA CABLEADO ARNEsES"),
    DAÑO_FUSIBLES("DAÑO FUSIBLES"),
    DAÑO_MODULOS("DAÑO MODULOS"),
    DAÑO_SENSORES("DAÑO SENSORES"),
    DAÑO_ACTUADORES("DAÑO ACTUADORES"),
    DAÑO_SISTEMA_DE_CARGA("DAÑO SISTEMA DE CARGA"),
    DAÑO_SISTEMA_AIRE_ACONDICIONADO("DAÑO SISTEMA AIRE ACONDICIONADO"),
    DAÑO_EN_SISTEMA_DE_AUDIO("DAÑO EN SISTEMA DE AUDIO"),
    TECHO_CORREDIZO("TECHO CORREDIZO"),
    OTROS("OTROS"),
    DAÑO_SISTEMA_DE_FRENOS("DAÑO SISTEMA DE FRENOS"),
    DAÑO_MOTOR("DAÑO MOTOR"),
    DAÑO_TAPICERIA("DAÑO TAPICERIA"),
    DAÑO_PUERTAS("DAÑO PUERTAS"),
    DAÑO_BODY("DAÑO BODY"),
    DAÑO_SUSPENSION("DAÑO SUSPENSION"),
    DAÑO_TRASMISION("DAÑO TRASMISION"),
    FALLO_COMPONENTE_OTROS("FALLO COMPONENTE OTROS"),
    FALLA_EN_SISTEMA_DE_TRANSFERENCIA("FALLA EN SISTEMA DE TRANSFERENCIA"),
    HUMEDAD_INTERNA("HUMEDAD INTERNA"),
    TAPACUBOS("TAPACUBOS"),
    CONTROLES_DE_ENCENDIDO("CONTROLES DE ENCENDIDO"),
    LLAVES_MATRIZ("LLAVES MATRIZ"),
    MANUALES_DE_PROPIETARIO("MANUALES DE PROPIETARIO"),
    TAPAS_GUARDACHOQUES("TAPAS GUARDACHOQUES"),
    TOPES_DE_CAUCHO("TOPES DE CAUCHO"),
    VINCHAS_DE_SUJECION("VINCHAS DE SUJECION"),
    CLIP_VARILLA_CAPO("CLIP VARILLA CAPO"),
    TAPAS_PORTA_HERRAMIENTAS("TAPAS PORTA HERRAMIENTAS"),
    GATA("GATA"),
    PALANCA_GATA("PALANCA GATA"),
    LLAVE_DE_RUEDAS("LLAVE DE RUEDAS"),
    GANCHOS_DE_REMOLQUE("GANCHOS_DE_REMOLQUE"),
    LOGOS("LOGOS"),
    PPF("PPF"),
    TAPA_MOTOR("TAPA MOTOR"),
    TAPA_RADIADOR("TAPA RADIADOR"),
    TAPA_ACEITE_MOTOR("TAPA ACEITE MOTOR"),
    TAPA_BORNE_BATERIA("TAPA BORNE BATERIA"),
    TAPA_TOMA_12V("TAPA TOMA 12V"),
    CUBRE_MALETERO("CUBRE MALETERO"),
    LLANTA_DE_EMERGENCIA("LLANTA DE EMERGENCIA"),
    TAPA_VALVULAS("TAPA VALVULAS"),
    PORTA_HERRAMIENTAS("PORTA HERRAMIENTAS"),
    TAPA_BALDE("TAPA BALDE"),
    INSONORIZANTE_CAPO("INSONORIZANTE CAPO"),
    TAPA_MANIJA_PUERTA("TAPA MANIJA PUERTA"),
    TAPA_TAPIZADOS("TAPA TAPIZADOS"),
    FAROS("FAROS"),
    MASCARILLAS("MASCARILLAS"),
    SENSORES("SENSORES"),
    ACTUADORES("ACTUADORES"),
    RADIO("RADIO"),
    VIDRIOS("VIDRIOS"),
    BATERIA("BATERIA"),
    COMPUTADORA_ECU("COMPUTADORA_ECU"),
    BOBINA("BOBINA"),
    SISTEMA_SRS("SISTEMA_SRS"),
    CAMARA_DE_RETRO("CAMARA_DE_RETRO"),
    SISTEMA_AC("SISTEMA_AC"),
    BODY("BODY"),
    MOTOR("MOTOR"),
    FRENOS("FRENOS"),
    SUSPENSION("SUSPENSION"),
    CAJUELA("CAJUELA"),
    SISTEMA_LIMPIA_PARABRISAS("SISTEMA LIMPIA PARABRISAS"),
    PUERTAS("PUERTAS"),
    CABINA("CABINA"),
    ;
    
    private String nombre;    

    private ParteVehiculoEnum(String nombre) {
        this.nombre = nombre;
    }
    
    public static ParteVehiculoEnum buscarPorNombre(String nombre)
    {
        for (ParteVehiculoEnum value : ParteVehiculoEnum.values()) {
            if(value.getNombre().equals(nombre))
            {
                return value;
            }
        }
        return null;
    }

    public String getNombre() {
        return nombre;
    }

    @Override
    public String toString() {
        return nombre;
    }
    
    
}
